### PR TITLE
SAN: Lien Text Update

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#21555

*Description of changes:*
- Small Label Update for Notice of Liens

Screenshot 2024-06-10 at 3 04 27 PM

Screenshot 2024-06-10 at 3 04 29 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1929-0oy526la.web.app

**Review by dimak1 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1929-0oy526la.web.app

**Review by doug-lovett — APPROVED** [review]
Fast work again.

**Comment by cameron-eyds** [comment]
> Fast work again.

I spent all day on this 😆

**Pull request merged**
