### PR TITLE
Mhr-Only Dashboard

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#17564

*Description of changes:*
- Allows for MHR table only to be displayed
- Adds simple test

*note:
* This work was brought over from PR: https://github.com/bcgov/ppr/pull/1518
* Includes a bit of UXA in the aforementioned PR.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1524-uw6ytivq.web.app

**Review by dimak1 — APPROVED** [review]
Looks good

**Comment by tlebedovich** [comment]
@cameron-eyds that spacing warms my heart, thank you. can move to RFQA!

**Comment by cameron-eyds** [comment]
> @cameron-eyds that spacing warms my heart, thank you. can move to RFQA!

hahaha, thank you!

**Pull request merged**
