### PR TITLE
Add Document Id to Staff Transfers

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17644

*Description of changes:*
- Add Doc Id for Transfers for Staff
- Add validation
- Add/update unit tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1548-3as870ga.web.app

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by RuoxuanPengBC — APPROVED** [review]
Looks good to me, great job

**Pull request merged**
