### PR TITLE
Update or Create Qs Records

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#17785

*Description of changes:*
- Update or create QS record based on if a record already exists.

*Note:*
- There is still some auth work to be complete in order to also reset or change the state of the staff task.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1542-sttc6qrp.web.app

**Review by dimak1 — APPROVED** [review]
Looks good.

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Pull request merged**
