### PR TITLE
Misc Transfer Updates to Transfer Details & Review

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#18220

*Description of changes:*
- Updates to Misc Transfer Types without Bill of Sale
- See ticket for details

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1846-l630su9i.web.app

**Review by doug-lovett — APPROVED** [review]
LGTM.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1846-l630su9i.web.app

**Pull request merged**
