### PR TITLE
Reset Amend Active Flag on Transport Init

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#20605

*Description of changes:*
- Reset amend active flag on transport init

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1814-yxf0uq9r.web.app

**Review by cameron-eyds — APPROVED** [review]
LG!

**Review by doug-lovett — APPROVED** [review]

**Comment by dimak1** [comment]
@cameron-eyds is it ok to merge, with failing codecov?

**Pull request merged**
