### PR TITLE
Product Type Change Handling

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#17194

*Description of changes:*
* Detects any changes in user flow, to prompt a confirm change dialog
* Restore previous product selection on cancel
* Keep product change on confirm
* Some additional unit testing
* Misc Qs Review UX updates

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1530-ksb051if.web.app

**Review by dimak1 — APPROVED** [review]
Looks good to me!

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by tlebedovich** [comment]
@cameron-eyds - looks good to me thanks

**Comment by cameron-eyds** [comment]
> @cameron-eyds - looks good to me thanks

Thank you for the quick review!

**Pull request merged**
