### PR TITLE
Home Dealers and Manufacturers - User Access Updates + Misc QA items

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* 
/bcgov/entity#16952
/bcgov/entity#17462

*Description of changes:*
* Updates dynamic content in QS information component for home dealers and manufacturers
* Updates Org LookUp functionality options: Disable manual entries and enforce lookup option only
* Include DBA conditionally based on property in model in PartyForm common component
* Minor styling and ux fixes

*QA fixes included:*
- /bcgov/entity#18926 : Fixes some minor validation items in make/model
- /bcgov/entity#18925 : Fixes scroll too reg item following an Exemption Filing

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]
LG!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1682-bzbwsyfj.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Pull request merged**
