### PR TITLE
Handle Draft MHR Re-Registrations

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#21392

*Description of changes:*
- Reuse Corrections flow for Draft MHR Re-Registrations

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1914-9yh3skmp.web.app

**Review by cameron-eyds — APPROVED** [review]
LGTM!

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
