### PR TITLE
Review and Submit Cancel Transport Permit

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#21011

*Description of changes:*
- Review and Confirm page update
- Update validations
- Submission of Cancel Transport Permits
- Unit tests

Screenshot 2024-05-15 at 08 12 33

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1875-wvuwl8y4.web.app

**Review by doug-lovett — APPROVED** [review]
LGTM.

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1875-wvuwl8y4.web.app

**Pull request merged**
