### PR TITLE
Transfer Type Validations + Flow Updates

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#15294

*Description of changes:*
* Implements additional type validations
* Includes state resets to unsupported types
* Includes Tooltips on Transfer types
* Misc filing bug fix for Staff Payment
* Implements Change and Cancel dialogs for Transfer Types
* Misc test updates

Screen Shot 2023-02-28 at 12 04 28 PM
Screen Shot 2023-02-28 at 12 03 02 PM
Screen Shot 2023-02-28 at 12 02 49 PM
Screen Shot 2023-02-28 at 12 02 39 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by doug-lovett** [comment]
Thanks for the screenshots. I see "Transfer to Executor =" in the new death types: should it be "Transfer to Executor -"?

**Comment by cameron-eyds** [comment]
> Thanks for the screenshots. I see "Transfer to Executor =" in the new death types: should it be "Transfer to Executor -"?

Good catch, i think so, thank you! 
Will fix :)

**Review by doug-lovett — APPROVED** [review]
Looks great, just the one comment which you already responded to.

**Review by owillborn — APPROVED** [review]
lgtm

**Pull request merged**
