### PR TITLE
Fix Group Validation in MHR Transfers

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17736

*Description of changes:*
- Fix Group validations for Transfers
- Add unit test to support the fix

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1580-sj7nm9dk.web.app

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Review by RuoxuanPengBC — APPROVED** [review]
looks great

**Pull request merged**
