### PR TITLE
Mhr History Setup

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#21949

*Description of changes:*
- Mhr History View
- Breadbrumb/footer/route/labels
- Feature Flagged route and btn in the Registrations Table (Staff Only)
- History request and Response Object interfaces
- Unit Testing

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1955-iam5of31.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1955-iam5of31.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1955-iam5of31.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Review by dimak1 — APPROVED** [review]
Looks great!

**Pull request merged**
