### PR TITLE
Status and Badge for Cancelled Transport Permit

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#21011

*Description of changes:*
- Update Status and Badge for Cancelled Transport Permit
- Add unit test
- Update Registration Type dropdown for QS (feedback from QA)

Screenshot 2024-05-22 at 06 57 31

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1888-nfuti2it.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Pull request merged**
