### PR TITLE
SBC: Remove Waive Tax Cert Permissions

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#23025

*Description of changes:*
- Remove SBC Staff from conditions to allow the option to WAIVE Tax Certificate
- Revert Help Content for SBC to QS Version

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2055-j9e27due.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2055-j9e27due.web.app

**Review by doug-lovett — APPROVED** [review]
Instant fix, fantastico!

**Pull request merged**
