### PR TITLE
MHR api new unit note endpoint changes

### PR DESCRIPTION
**Pull request by doug-lovett**
*Issue #:* /bcgov/entity#16507

*Description of changes:*
- New api endpoint for unit notes
- Refactor note json 
- Update search and registration to use new note json definition

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Lookin gooooood!

**Review by dimak1 — APPROVED** [review]
Nice, good work!

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1372-4uwxksk9.web.app

**Review by orelbn — APPROVED** [review]

**Pull request merged**
