### PR TITLE
A11Y: V-Menu Navigation Fixes

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#21289

*Description of changes:*
- Updates the location of events in V-Menu items to facility accessibility through Tabbing and Up/Down Arrows. 
(See ticket for more thorough documentation on the issue/solution)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1937-9ev8c45x.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by dimak1 — APPROVED** [review]
LG!
It might help with other small enhancements in dropdowns, when sometimes it does not register the click because clicking are does not cover the whole row.

**Comment by cameron-eyds** [comment]
> LG! It might help with other small enhancements in dropdowns, when sometimes it does not register the click because clicking are does not cover the whole row.

Definitely, a good rule of thumb to go as root element as possible with the event binding!

**Pull request merged**
