### PR TITLE
Updates for Change Owner in Transfers

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#16140

*Description of changes:*
- Make fixes to Joint Tenants Transfer flow when Changing Owner

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1595-88c2vp4t.web.app

**Review by doug-lovett — APPROVED** [review]

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Review by RuoxuanPengBC — APPROVED** [review]
Looks great

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1595-88c2vp4t.web.app

**Pull request merged**
