### PR TITLE
Attention Ref Number on the Review screen

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* /bcgov/entity#13878

*Description of changes:*
- Add Attention or Reference Number section on the Review screen
- Add validation
- Add unit tests

### Screenshots

Screen Shot 2022-10-26 at 3 31 44 PM

Screen Shot 2022-10-26 at 3 33 54 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good!
We really should have made this section it's own component :)

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Comment by dimak1** [comment]
> Looks good! We really should have made this section it's own component :)

@cameron-freshworks yea, even UI design says reuse component from Registrations, which we don't have 😃 You want me to refactor and make one?

**Comment by cameron-eyds** [comment]
> > Looks good! We really should have made this section it's own component :)
> 
> @cameron-freshworks yea, even UI design says reuse component from Registrations, which we don't have 😃 You want me to refactor and make one?

@dimak1 Your call, totally up to you!

**Comment by dimak1** [comment]
@cameron-freshworks let's merge as is.

**Review by owillborn — APPROVED** [review]
Looks good to me!

**Review by ChasBoucher — APPROVED** [review]
Looks good

**Pull request merged**
