### PR TITLE
Mhr Status Correction UXA

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#19510

*Description of changes:*
* Minor styling/content adjustments to Status Correction Component
* Global font size change for UpdateBadge

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1758-j4hj71v8.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1758-j4hj71v8.web.app

**Review by dimak1 — APPROVED** [review]
LG!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1758-j4hj71v8.web.app

**Pull request merged**
