### PR TITLE
Puba Framework + Misc Correction Corrections

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#20060

*Description of changes:*
* PUBA Setup and Initialization: includes fees, breadcrumbs, labels etc
* Some minor Correction bug fixes: see 20500, 20525* 
* PUBA unit testing

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by doug-lovett — APPROVED** [review]
Easy peasy as someone likes to say.

**Comment by cameron-eyds** [comment]
> Easy peasy as someone likes to say.

hahaha, exactly!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1804-qh862529.web.app

**Pull request merged**
