### PR TITLE
Update landmarks + Skip to Main Content link

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#21791

*Description of changes:*
- Update landmarks + Skip to Main Content link

Screenshot 2024-07-09 at 11 21 56

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by doug-lovett — APPROVED** [review]
Looks great

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1973-8ya0d1kp.web.app

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by dimak1** [comment]
Fixed the styling for SbcSystemBanner after it was moved out of `<main>`. Resolved small conflicts.
Screenshot 2024-07-15 at 05 28 52

**Pull request merged**
