### PR TITLE
MHR Info page for Exempt Homes

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#19140

*Description of changes:*
- Use new `exemptDateTime` when displaying the date of exemption
- Update dropdown label to 'Re-register Home'
- Text show/hide based on exemptions status
- Unit test

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1729-1ngkvupl.web.app

**Review by cameron-eyds — APPROVED** [review]
LGTM!
Perhaps some of the conditions had an impact in the tests however.

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1729-1ngkvupl.web.app

**Pull request merged**
