### PR TITLE
Transfer to Surviving Joint Tenants: Lawyer/Notary Restrictions

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#17951

*Description of changes:*
* Disable Home Owner changes when Lawyer and Notary: Transfer to Surviving Joint Tenant Transfer
* Lint/clean up

/bcgov/entity#19706
* Fix display bug in MHR Information Location Review

Screenshot 2024-02-08 at 6 21 35 PM

Screenshot 2024-02-08 at 6 23 08 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1728-jbj43p9d.web.app

**Review by dimak1 — APPROVED** [review]

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1728-jbj43p9d.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1728-jbj43p9d.web.app

**Pull request merged**
