### PR TITLE
Transfer Owner Changes: Misc Bug Fixes 

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:*
*Description of changes:*
-  /bcgov/entity#24514 : Fixed Payload for Edits made during SJT Transfer
-  /bcgov/entity#24513 : Fix available menu items in Death Transfers
-  /bcgov/entity#24304 : Removes Role Edits on Existing owners in OTHER Transfer types 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by doug-lovett — APPROVED** [review]
Fantastic!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2076-oiverojf.web.app

**Review by flutistar — APPROVED** [review]
Looks good

**Pull request merged**
