### PR TITLE
Fix Additional Name in Transfers

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#16795

*Description of changes:*
- Fix Additional Name when working with Transfers
- Fix not to allow Home Owners Role changes for Surviving Owner Transfer 
- Other fixes
- Unit test updates

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by orelbn — APPROVED** [review]
Looks great!

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1422-r8fswezp.web.app

**Review by doug-lovett — APPROVED** [review]

**Pull request merged**
