### PR TITLE
MHR Registration Table updates for Transport Permit

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#18347

*Description of changes:*
- Update css class for error text (`invalid-color` class does not exist)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by dimak1** [comment]
Pending response from Liz, hence draft PR.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1719-rgotrex1.web.app

**Review by doug-lovett — APPROVED** [review]
As small as it gets.

**Review by cameron-eyds — APPROVED** [review]
Spectacular! 
Now enjoy the weekend 😆

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1719-rgotrex1.web.app

**Pull request merged**
