### PR TITLE
Pre-fill Additional Name for Admin Transfers (LETA)

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#15808

*Description of changes:*

- Pre-fill suffix/additional name and owner type for Admin Transfer (LETA)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
LG!

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1336-x8ypf2fc.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1336-x8ypf2fc.web.app

**Review by orelbn — APPROVED** [review]
LGTM! Nice clean up

**Pull request merged**
