### PR TITLE
Removes Land Lease from MhrInformation page

### PR DESCRIPTION
**Pull request by orelbn**
*Issue #:* /bcgov/entity#17035

*Description of changes:*
- Removes Land Lease Component from Mhr Information page

Before:
image

After:
image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1452-jr0biq4q.web.app

**Review by cameron-eyds — APPROVED** [review]

**Review by doug-lovett — APPROVED** [review]

**Review by dimak1 — APPROVED** [review]

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1452-jr0biq4q.web.app

**Pull request merged**
