### PR TITLE
Mhr History Tabs (Common Components)

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#21851

*Description of changes:*
- Common configurable tab component
- Simple configurable table component (future state to include styling/slots for our own requirements)
- Configurations and implementation of tab/table components for Mhr History
- Unit testing

Screenshot 2024-06-28 at 12 42 34 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1958-l9ygsnol.web.app

**Review by doug-lovett — APPROVED** [review]
C'est magnifique!

**Review by dimak1 — APPROVED** [review]
Looks great! Nice work.

**Pull request merged**
