### PR TITLE
QA Items : Re-Issue Permit and Tax Certificate

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#23025

*Description of changes:*
- Include waived Certificate content on review screen
- Preserve Submitting Party on Review for Extend Permit

Screenshot 2024-10-18 at 7 25 11 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by flutistar — APPROVED** [review]
Looks good to me!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2043-qi2509s1.web.app

**Pull request merged**
