### PR TITLE
Client Corrections and Cancelled Unit Note Handling

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Description of changes:*
*Issue #:* /bcgov/entity#19620
- Implements variances for Client Corrections (ie staff payment, validations, Fee Summary, Text content)
- Improves location change corrections comparisons
- Fix bug where correction content would carry between corrections
- Client Correction Unit Tests

*Issue #:* /bcgov/entity#19618
- Minor updates to Unit Note panels to include reason for Cancellation and Reg Number
- Updated tests

Screenshot 2024-03-27 at 7 07 39 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1802-yzvuluyd.web.app

**Review by doug-lovett — APPROVED** [review]
Very nice. Fast work.

**Comment by cameron-eyds** [comment]
> Very nice. Fast work.

Thank you!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1802-yzvuluyd.web.app

**Pull request merged**
