### PR TITLE
Update MHR Reg Table filter for QS

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#18386

*Description of changes:*
- Update filter in MHR Reg Table for QS

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
LG! Ez 2 points

**Comment by dimak1** [comment]
> LG! Ez 2 points

@cameron-eyds downgraded to 1 point to be fair 😄

**Comment by cameron-eyds** [comment]
> > LG! Ez 2 points
> 
> @cameron-eyds downgraded to 1 point to be fair 😄

I would leave it! Sometimes estimates are high, sometimes low. All comes out in the wash :)

**Comment by dimak1** [comment]
> > > LG! Ez 2 points
> > 
> > 
> > @cameron-eyds downgraded to 1 point to be fair 😄
> 
> I would leave it! Sometimes estimates are high, sometimes low. All comes out in the wash :)

If I see at least one feedback comment, I will immediately increase back to 2 points 🤣

**Review by doug-lovett — APPROVED** [review]
LG.

**Pull request merged**
