### PR TITLE
Create New Permit UXA

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#21477

*Description of changes:*
- UXA items listed in ticket
- Vue computed value reference bug fix, found during local testing

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2039-i0lafx7n.web.app

**Review by doug-lovett — APPROVED** [review]
Perfecto!

**Review by flutistar — APPROVED** [review]
Looks good

**Pull request merged**
