### PR TITLE
DRS - Document ID

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#23682

*Description of changes:*
- Updated Document ID in the following flows:

MH Registration
Transfers
Permits / Location Changes
Unit Notes
Exemptions

Updated rules and validations
Modify the validation flag to consider absent document identifier
Remove document identifier property from payloads
Refactor and remove duplicate instances of DocumentID and use the component throughout

Screenshot 2024-10-23 at 1 55 45 PM

Screenshot 2024-10-23 at 1 55 33 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2046-iul5b4ds.web.app

**Review by flutistar — APPROVED** [review]
LGTM

**Review by doug-lovett — APPROVED** [review]
Wonderful!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2046-iul5b4ds.web.app

**Pull request merged**
