### PR TITLE
Transfer due to Sale or Gift for QS

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#15983

*Description of changes:*
- Styling updates for Transfers for QS

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1782-rwj66nk4.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1782-rwj66nk4.web.app

**Pull request merged**
