### PR TITLE
Unit Tests for Transfers with Confidential Notes

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17907

*Description of changes:*
- The bug described in the ticket seems to be gone (due to previous PRs), so I added more tests to make sure it won't come back
- Re-add Death Certificate validation that was missing
- Small tests cleanup (mock -> mocked) for consistency

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by doug-lovett — APPROVED** [review]

**Review by cameron-eyds — APPROVED** [review]
Looks great, nice work. Can never have enough tests 🙏

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1567-2o6ucfkq.web.app

**Review by RuoxuanPengBC — APPROVED** [review]
Looks great

**Pull request merged**
