### PR TITLE
QS Status Message Preference Update

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#16949

*Description of changes:*
* Update misc preferences to consider account id, to differentiate between multiple accounts with varying status of application status.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1496-ek8oto15.web.app

**Review by orelbn — APPROVED** [review]
LGTM!

**Review by doug-lovett — APPROVED** [review]
Magical.

**Pull request merged**
