### PR TITLE
Updates to Residential Exemption with Lien

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17744

*Description of changes:*
- Updates to Residential Exemption with Lien

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1621-rev6egpo.web.app

**Review by cameron-eyds — APPROVED** [review]
LGTM!

**Review by RuoxuanPengBC — APPROVED** [review]
looks great!!!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1621-rev6egpo.web.app

**Comment by dimak1** [comment]
@cameron-eyds please have another look - I did some refactoring (LienAlert component) and added new code. Thanks!

**Review by cameron-eyds — APPROVED** [review]
New commit looks great 🦖

**Pull request merged**
