### PR TITLE
Additional Tests + Small Style Fix

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 

- bcgov/entity#17368

*Description of changes:*
- Unit tests to make sure Unit Notes do not show Additional Remarks checkbox
- Styling fix

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1528-2zei7a44.web.app

**Review by cameron-eyds — APPROVED** [review]
Looks good 👍

**Review by doug-lovett — APPROVED** [review]

**Review by RuoxuanPengBC — APPROVED** [review]
Looks good

**Pull request merged**
