### PR TITLE
MHR Submission fixes for Additional Name

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17154

*Description of changes:*
- Remove instances where description or suffix are altered.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1450-kpmmyqdi.web.app

**Review by orelbn — APPROVED** [review]
Looks good!

**Review by doug-lovett — APPROVED** [review]
LGTM

**Review by cameron-eyds — APPROVED** [review]

**Pull request merged**
