### PR TITLE
A11y Unit Testing - Timeboxed

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#17892

*Description of changes:*
- Implements Axe unit testing integration
- This was time-boxed, to give us an idea of what sort of scope we are dealing with in order to apply an A11Y unit test to our test suites. 
- After a few unit tests, typical results required a dozen small items to fix but often in components that nested and not always the component subject of the test itself. This is due to a 'mounted' approach to unit testing which better supports our component library Vuetify. 
- Now that we have an idea of how and how much, we can properly estimate the remaining tests to tackle over time, or find a way to include in future tasks.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2014-mi67kmwo.web.app

**Review by flutistar — APPROVED** [review]
LGTM

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Pull request merged**
