### PR TITLE
Registration Table: Preserve filters for staff only

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#21326

*Description of changes:*
- Clear Registration Table Filters when User is not PPR Staff 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by flutistar — APPROVED** [review]
LGTM.

I believe I didn't remove `UITransferTypes`.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2010-p43hvdrq.web.app

**Comment by cameron-eyds** [comment]
> LGTM.
> 
> I believe I didn't remove `UITransferTypes`.

Totally all good, i'm not sure why it wasn't picked up in the CI. 
Usually just run lint before committing!

**Review by doug-lovett — APPROVED** [review]
LGTM

**Comment by flutistar** [comment]
> > LGTM.
> > I believe I didn't remove `UITransferTypes`.
> 
> Totally all good, i'm not sure why it wasn't picked up in the CI. Usually just run lint before committing!

Yep I will!

**Pull request merged**
