### PR TITLE
Add payment info for Unit Note submission

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17217

*Description of changes:*
- Add payment info as request param to Unit Note submission API call

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1598-ie0orxim.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
