### PR TITLE
Transfer Race Condition Handling

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#15846

*Description of changes:*
* Unable to save Transfer due to out of date Home Owners Information handling
* Dialog with MHR Number and functionality to reset to baseline MHR (Also clears draft in the event on of the users racing was on a draft)

*Note:*
- It's a very unlikely scenario, even if two users open the same registration at the same time, anytime a transfer type is selected the data is fetched and up to date. Requires two users to both have selected a transfer type at the same time and proceed from there but alas, the ticket was made.
- Drafts are also handled at the entry point, so that will probably be like 99% of scenarios. 

Screenshot 2024-02-02 at 7 42 06 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1716-cbk662b1.web.app

**Review by doug-lovett — APPROVED** [review]
Outstanding.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1716-cbk662b1.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1716-cbk662b1.web.app

**Pull request merged**
