### PR TITLE
Make Remarks required for Public Note only

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* /bcgov/entity#17694

*Description of changes:*
- Remarks are required for Public Note
- Unit tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1540-bb7zuhng.web.app

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Review by doug-lovett — APPROVED** [review]
LGTM

**Pull request merged**
