### PR TITLE
NonRes Exemption Updates + Transfer Feedback Content 

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Description of changes:*
*Issue #:* /bcgov/entity#17508
- Non Res Exemptions Framework items (Note: Does NOT include submissions or review content- Will be PR part2)
- Version bump

*Issue #:* /bcgov/entity#20878
- Pre-filled role bug fix when Affe and Notice of Tax Sale present

*Issue #:* /bcgov/entity#20880
*Issue #:* /bcgov/entity#20881
- Home Owners Content update as per client MHR Feedback

Screenshot 2024-04-17 at 12 00 51 PM

Screenshot 2024-04-17 at 12 00 14 PM

Screenshot 2024-04-17 at 11 59 48 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1833-mwsk5hjt.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1833-mwsk5hjt.web.app

**Review by doug-lovett — APPROVED** [review]
Very nice. Fast work.

**Comment by cameron-eyds** [comment]
> Very nice. Fast work.

Thank you for the quick review!

**Pull request merged**
