### PR TITLE
Submissions Lien Check Update

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#22792

*Description of changes:*
- At the point of submissions don't scroll too or present errors when the lien isn't a blocked type

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by flutistar — APPROVED** [review]
LGTM!

**Review by doug-lovett — APPROVED** [review]
One more time with feeling!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2008-9pngidsi.web.app

**Pull request merged**
