### PR TITLE
PPR Validation Scrolling / Search Highlight / MF Address Comparison Update

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#19803

*Description of changes:*
- Updated border-error-left styling to give some margin above scrolled to element on validation scrolls
- Includes scroll-to in PPR registrations/discharges at submission (was already in Amendments/Renews)
- Adds error borders to incomplete parties

 /bcgov/entity#22240
- Omit Postal code from MF Address Comparison to support legacy data where it could be absent

 /bcgov/entity#19087
- Search Highlight and scroll to
Screenshot 2024-07-10 at 10 29 22 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]
LG!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1975-s39an2ng.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1975-s39an2ng.web.app

**Pull request merged**
