### PR TITLE
Transport Permit Review & Confirm for QS

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#18345

*Description of changes:*
- Updates to Review and Confirm page for QS
- Payload updates
- Small styling fixes
- Unit tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1727-g5fqq8uy.web.app

**Review by doug-lovett — APPROVED** [review]

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1727-g5fqq8uy.web.app

**Pull request merged**
