### PR TITLE
Affe Restrictions and A11Y adjustment

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#23294

*Description of changes:*
- Restriction Owner Removal for Executors and Admins in Trans Affi.
- Minor A11Y Screen Reader adjustment for Search History table pdf button.

Screenshot 2024-09-20 at 5 01 10 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2026-6h9386dt.web.app

**Review by doug-lovett — APPROVED** [review]
Easy peasy.

**Review by flutistar — APPROVED** [review]
LGTM

**Pull request merged**
