### PR TITLE
MHR api TRANS validation update to work with UI.

### PR DESCRIPTION
**Pull request by doug-lovett**
*Issue #:* /bcgov/entity#17071

*Description of changes:*
- Update to TRANS validation to work with UI requests where all owner groups are submitted including ones that do not change.
- Minor fixes to draft sorting, filtering.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by orelbn — APPROVED** [review]
Looks great thanks for adding the draft fixes!

**Review by dimak1 — APPROVED** [review]
Looks good.

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1428-5j7m81vk.web.app

**Pull request merged**
