### PR TITLE
API unit note caution updates and bug fixes.

### PR DESCRIPTION
**Pull request by doug-lovett**
*Issue #:* /bcgov/entity#16831
                  /bcgov/entity/#16832
                 /bcgov/entity/16910

*Description of changes:*
- Minor unit note registration and search unit note section report updates.
- Caution unit note rule updates:
	Expiry end of day
	CAUC and CAUE can be created after a CAU has expired.
	Multiple active CAU registrations are allowed.
	Cancelling a CAU/CAUC/CAUE cancels all active CAU/CAUC/CAUE registrations.
- Bug fix on saving manufacturer MHREG with a draft.
- 16910 bug fix non-Canada location province codes in search showing country of Canada.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]
Good stuff.

**Review by orelbn — APPROVED** [review]
Very Nice!

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by orelbn** [comment]
Can you please update the formatting for the issue #.

**Pull request merged**
