### PR TITLE
General MHR Items + Misc PPR QA items

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#18936  /bcgov/entity#19010  /bcgov/entity#18913  /bcgov/entity#18919  /bcgov/entity#18916

*Description of changes:*
* General MHR items which include updated validations and some home owners functional bugs
* General app scroll to effects built into nav helper
* PPR styling class updates to restore red text and error borders
* Contact expansion bug fix - display content in slot
* Added two util functions (one to filter duplicates in lists, another a scroll to top helper)
* Minor test updates
* Default route to Dashboard to help staff whom are already authenticated entering the application from being redirect back to auth
* Load MHR table data after MH Reg filings, previously was not displaying recently filed filings (bug exists in test)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1661-fu5f6981.web.app

**Review by doug-lovett — APPROVED** [review]
Outstanding. Mr. Clean ............. Up

**Comment by cameron-eyds** [comment]
> Outstanding. Mr. Clean ............. Up

hahah 
I'll be looking like Mr Clean by the time this upgrade is complete :)

**Comment by seeker25** [comment]
I already look like Mr Clean

**Pull request merged**
