### PR TITLE
Transfers: Owner Contact Info Editing

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#24304

*Description of changes:*
- Enables the Contact Information Editing for Owners in ALL Transfer Types
- Minor Payload refactoring to include previousOwnerId
- Refactoring on Add Edit Owner to disable name field editing.
- Minor copy and unit test updates

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2067-dq2p11e3.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2067-dq2p11e3.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Review by flutistar — APPROVED** [review]
LGTM

**Pull request merged**
