### PR TITLE
Staff Payment Display Bug

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#13133

*Description of changes:*
- Reset state that hides/shows Staff Payment Component for Staff Mhr Search

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1983-1gnel58t.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by flutistar — APPROVED** [review]
Looks good to me

**Pull request merged**
