### PR TITLE
User Access Select + Nav/Footer CleanUp

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#17179

*Description of changes:*
- Access Select Validations.
- Save and Set selected type to store.
- Basic User Access Store Setup.
- Tab-able ToolTip content for accessibility .
- Basic nav helper.
- Clean up of redundant footer prop  statement type and it's implementations.

*TESTING NOTES:*
- Use BCREG0018/MyMhrTestBusiness for accessible account. 
- If having issues setting the specific account via the preview url, append the url with: `?accountid=3144`
- To verify footer and nav configurations for refactored code, see PPR Registrations Footers/Steppers.
- Figma designs for reference: https://www.figma.com/file/0sD17BVTK7OwTqPRsAoreu/MHR-Account-User-Flow?type=design&node-id=461-39243&mode=design&t=IeGd9oPcNb2kuOM2-0

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1462-6lmp1cb1.web.app

**Review by orelbn — APPROVED** [review]
Amazing! 🔥

**Review by dimak1 — APPROVED** [review]

**Comment by tlebedovich** [comment]
@cameron-eyds - UXA feedback on this selection screen:

Screen Shot 2023-07-31 at 1 42 43 PM

**Comment by cameron-eyds** [comment]
@tlebedovich Are you looking in DEV or the preview URL?
I'm guessing DEV 😁 

Check out the temporary preview URL above which should reflect the code changes in this PR. Some may still apply but your screenshot is from the initial placeholder view of the component.

**Comment by tlebedovich** [comment]
@cameron-eyds - you are right, when I used the account dropdown to switch users it moved me to dev, will relook, thanks

**Comment by tlebedovich** [comment]
@cameron-eyds - UXA screenshot updated to reflect test link. looks great, just minor tweaks.

**Review by doug-lovett — APPROVED** [review]
Fantastic

**Comment by cameron-eyds** [comment]
> @cameron-eyds - UXA screenshot updated to reflect test link. looks great, just minor tweaks.

Thank you! 
The beauty of this process, can have these fixes in asap without any further PR's.

**Comment by tlebedovich** [comment]
@cameron-eyds - one additional AA note - temporary link is gone now for me but could you check to make sure user can tab/keyboard through this screen to select any of the 3 radio buttons (in addition to the other buttons/link on the page). It may be doing that already. If its a big deal to fix, we can add this to a future ticket.

**Comment by cameron-eyds** [comment]
@tlebedovich Currently the tabbing does highlight the tooltip as requested by designs. The radio btns do not have that built in by default however to tab through and have them selected, so it will be additional scope to implement this. 

I'll have to verify with Melissa, it's ok to add this scope here.
That being said, this wouldn't be behaviour implemented in all instances of radio buttons throughout the application. Is the intention to start building in this type of accessibility in all instances of the radio buttons?

**Comment by tlebedovich** [comment]
@cameron-eyds yes, eventually we need all of our apps/page to be able to be keyboarded and tabbed through to improve our AA compliance, so I thought since this was a net new single page we could maybe add it in. But we can wait until Melissa is back to discuss when/where to start AA improvements. Its a meeting we need to have together with her and devs and design. But we have our first tab friendly tool tip, so that's a start!

**Comment by cameron-eyds** [comment]
> @cameron-eyds yes, eventually we need all of our apps/page to be able to be keyboarded and tabbed through to improve our AA compliance, so I thought since this was a net new single page we could maybe add it in. But we can wait until Melissa is back to discuss when/where to start AA improvements. Its a meeting we need to have together with her and devs and design. But we have our first tab friendly tool tip, so that's a start!

Sounds good, absolutely! Lets just confirm with Melissa in the morning. 
Would be a good time to start setting that standard!

Just to add to this, what IS currently functional:

A user can TAB into the radio group (think of this as the component) and then use the UP and DOWN keys to navigate through radio selections, which will also auto-select. I'm not sure if this acceptable or it HAS to be the TAB key that does the selecting. Thats just how it works by default.

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1462-6lmp1cb1.web.app

**Pull request merged**
