### PR TITLE
Additional Remarks for Notice of Tax Sale

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17127

*Description of changes:*
- Add checkbox for Additional Remarks for TAXN
- Append Additional Remarks on Review screen and submission
- Add unit tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1505-ur2uwk4b.web.app

**Review by cameron-eyds — APPROVED** [review]
Looks great 👍

**Review by doug-lovett — APPROVED** [review]
Very nice.

**Review by orelbn — APPROVED** [review]
Looks good!

**Pull request merged**
