### PR TITLE
Preserve Table Filters for both PPR/MHR

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#21326

*Description of changes:*
- Refactors to preserve Table Filters for both PPR and MHR Registration Table instances
- Preserves ALL filters throughout filings, route changes, registrations etc.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by flutistar — APPROVED** [review]
LGTM

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2005-ui0ygly2.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2005-ui0ygly2.web.app

**Pull request merged**
