### PR TITLE
update footer

### PR DESCRIPTION
**Pull request by garyfan1**
*Issue #:* /bcgov/entity#12087

*Description of changes:*
update the footer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by cameron-eyds** [comment]
Hey Gary, could you confirm what version of Node you have installed? 
The p-lock diff looks quite large. 
I'm sure its just due to the Common Components being a rather large dependency, but wanted to confirm, thanks!

**Comment by garyfan1** [comment]
image
10.19.0

**Comment by cameron-eyds** [comment]
> image 10.19.0

Ah ok, so this will potentially have an impact. 
Previously a vulnerability was exposed on Versions of Node before `14.17.5`. 
There is a request to update Node to the most recent but to start could you update your Node version to `14.17.5`. 
Afterwards, please clear your `node_modules` (`rm -rf node_modules`) and `npm i` and commit.

**Comment by garyfan1** [comment]
updated the node version and reinstall node_modules!

**Comment by cameron-eyds** [comment]
@garyfan1 Right on, the P-lock diff looks much smaller now! Ty

To highlight a risk here, this specific dependency is potentially very large. 
For some context, it's a package containing many Common Components, which are not individually versioned, so updating this blanket version will in turn update ALL the Common Components used in this in project. 

Point being, please take a little extra time to review the App and ensure no wonky behaviour or errors in console or terminal when running locally. 
A good starting point to identifying what this project uses from that package is to search for the Imports through the app, so you can reference what to verify. 
ie in `app.vue` see all the imports from `sbc-common-components/src/components/`

May be tedious, but will prevent any surprise bugs due to updating a Common Component you didn't expect too.

**Comment by garyfan1** [comment]
I checked what common components has changed from 2.4.40 to 2.4.45 [here](https://github.com/bcgov/sbc-common-components/compare/2.4.40...2.4.45)
Footer and headers are the only ones we are using and when I click around the website, I'm just seeing lots of log messages and no errors/warnings.

**Comment by cameron-eyds** [comment]
> I checked what common components has changed from 2.4.40 to 2.4.45 [here](https://github.com/bcgov/sbc-common-components/compare/2.4.40...2.4.45) Footer and headers are the only ones we are using and when I click around the website, I'm just seeing lots of log messages and no errors/warnings.

Perfect, thanks for reviewing!

**Review by cameron-eyds — APPROVED** [review]
Looks good, thanks for the thoroughness here.

Don't worry about the CodeCov report, it's reporting on code unchanged 🤷

**Review by dimak1 — APPROVED** [review]

**Pull request merged**
