### PR TITLE
Add Focus State for Tabbable Elements

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#21781

*Description of changes:*
- Use :focus-visible pseudo class to apply outline styling only on Tab 
- Vue plugin to add event listeners for v-text-fields to fulfill the Tab-only requirement (no focus ring on mouse click)

Screenshot 2024-07-03 at 14 05 19

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by dimak1** [comment]
@cameron-eyds just some context here. The requirement was to apply styling only when tabbing into the fields or buttons. The pseudo class :focus-visible is built specifically for it, and I was able to use it for buttons. However, for text input fields, it does not work - the :focus and :focus-visible are applied at the same time, so there is no way to differentiate it. 

To solve this, I created a plugin that would add tab event listeners to all v-text-fields and style the fields on tab only. It could also be achieved via directive, but then we need to add it to all v-text-fields, which is more work.

Let me know if you have questions/comments. Thanks!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1963-xvx3zta2.web.app

**Comment by cameron-eyds** [comment]
Code looks fine but some styling on the Registration Table Tabs is gone. The inactive tab would shrink slightly lower than the active tab. Maybe it's ok, would confirm with @LizGovier

**Review by cameron-eyds — APPROVED** [review]
Code looks good but pending approval from @LizGovier with regards to the removal of the tab styling.

Edit* FWIW it's a very small thing and the tab designs for our MHR history don't include shrink/grow styling, so hopefully all good with design.

**Comment by dimak1** [comment]
@cameron-eyds thanks, tabs were tricky and bunch of styles needed to be updated in order for focus outline to show. I left some comments for Liz in the ticket, so we'll see.

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1963-xvx3zta2.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1963-xvx3zta2.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1963-xvx3zta2.web.app

**Pull request merged**
