### PR TITLE
Cancel Note Landing and Review pages + Submission

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#16799

*Description of changes:*
- Cancel Unit note flow
- Landing page updates
- Review Page updates
- Submission
- Tests updates

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1517-pzidnq3u.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1517-pzidnq3u.web.app

**Review by orelbn — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1517-pzidnq3u.web.app

**Review by cameron-eyds — APPROVED** [review]
Looks good 👍

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1517-pzidnq3u.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1517-pzidnq3u.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1517-pzidnq3u.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1517-pzidnq3u.web.app

**Pull request merged**
