### PR TITLE
Draft Order and Field Validation QA

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#18291

*Description of changes:*
- Order drafts by last updated dateTime and non drafts by create dateTime
- Fix consideration field validation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1945-b7jkmgjz.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1945-b7jkmgjz.web.app

**Pull request merged**
