### PR TITLE
Error Contact Update

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#14712

*Description of changes:*
* ~The ticket describes updating a phone number however that phone number was already present, so this work just~ ~removes the phone contact for SBC IT, which was not wanting to be included in the contact.~
* Updated local number as per recent discussions in ticket.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by ChasBoucher — APPROVED** [review]
Looks Good

**Review by doug-lovett — APPROVED** [review]
LGTM.

**Review by dimak1 — CHANGES_REQUESTED** [review]
Melissa just commented to keep the updated local number.

**Comment by cameron-eyds** [comment]
> Melissa just commented to keep the updated local number.

You bet, thank you!
Updated as per recent discussion 👍

**Review by dimak1 — APPROVED** [review]

**Pull request merged**
