### PR TITLE
Add Amend Trans Permit restrictions for QS and Sbc

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#21428

*Description of changes:*
- Add Amend Trans Permit restrictions for QS and Sbc roles
- Add unit tests

Screenshot 2024-06-11 at 09 11 14

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1933-1g47rc2p.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1933-1g47rc2p.web.app

**Pull request merged**
