### PR TITLE
Fix Tax Certificate Validation

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* /bcgov/entity###

*Description of changes:*
- Fix Tax Certificate validation for Transport Permit

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1747-vegju5fg.web.app

**Review by doug-lovett — APPROVED** [review]
Rolls!

**Pull request merged**
