### PR TITLE
Registration Table Preferences

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#20579

*Description of changes:*
* Clean up/fix up Registration Table User preferences preservation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]

**Comment by cameron-eyds** [comment]
Codecov is failing to upload, repeatedly. Going to ignore it for my sanity.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1812-doryl5dl.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
