### PR TITLE
Optional Person Giving Notice & Hide Effective Date

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17037
- bcgov/entity#17049

*Description of changes:*
- Optional Person Giving Notice for Decal Replacement (102), Public Note (NPUB), Confidential Note (NCON)
- Update Review and Confirm screen
- Hide Effective Date Time component for Decal Replace and Public Notes
- Add more tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1460-dfue9eqw.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1460-dfue9eqw.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1460-dfue9eqw.web.app

**Review by cameron-eyds — APPROVED** [review]
LG!

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1460-dfue9eqw.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by orelbn — APPROVED** [review]
Looks great!

**Pull request merged**
