### PR TITLE
Permit ReIssue - Create "New" Permit Validation

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity###

*Description of changes:*
- Minor validation bug fix
- To unblock NEW PERMITS creation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2065-jrd2uvdp.web.app

**Review by flutistar — APPROVED** [review]
LGTM

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
