### PR TITLE
13670 mhr UI update location types

### PR DESCRIPTION
**Pull request by ChasBoucher**
*Issue #:* /bcgov/entity#13670

*Description of changes:*

- Update MHR location types enum to match api requirements.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — COMMENTED** [review]
Do we need to update the watchers in `HomeLocationType` as well?

*Edit - After a quick look, the watchers do use the values vs the enum itself. So will need to update there as well i believe.

**Review by dimak1 — APPROVED** [review]

**Comment by owillborn** [comment]
Aside from Cameron's comment, looks good to me!

**Review by doug-lovett — APPROVED** [review]
looks good

**Review by owillborn — APPROVED** [review]
Looks solid

**Comment by ChasBoucher** [comment]
The watchers seem fine.  They evaluate to the correct values and the store is being updated correctly.

**Comment by cameron-eyds** [comment]
> The watchers seem fine. They evaluate to the correct values and the store is being updated correctly.

@ChasBoucher please have another look at the watcher on line 261 in HomeLocationType.
It references the string value of the enum `otherType` but you've changed the value in the enum here to `other`. 
Maybe i'm just being over cautious, it is most likely just due to a property name being similar name as the value :)
But if you've verified than all good!

**Review by cameron-eyds — APPROVED** [review]

**Pull request merged**
