### PR TITLE
Dealer Civic Location Addition

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#24171

*Description of changes:*
- Includes Civic Address for Dealers
- includes additional address in review and payload
- updated unit test

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2061-svbqg95h.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Review by flutistar — APPROVED** [review]
LGTM

**Pull request merged**
