### PR TITLE
SAN AMEND: UXA Feedback

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#

*Description of changes:*
- Some Badge spacing Styling
- Don't show Added Orders badge on Added Notices
- Preserving Panel expansion on order removal
- min char length added to OPTIONAL Effect of Order field - ie only validate when characters present
- Don't show amended badge or action on Parent notice when child orders edited - Modified logic to include these changed notices into add/remove notice payload.
- Updated Fees

Screenshot 2024-06-06 at 9 04 32 AM

Screenshot 2024-06-06 at 9 05 17 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1917-rpramtxt.web.app

**Review by dimak1 — APPROVED** [review]
LG!

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
