### PR TITLE
Add a Manufacturer Registration Success dialog

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17783

*Description of changes:*
- Add a Success Registration dialog for Manufacturer Registration
- Add a permanently hide dialog option by extending functionality of a base dialog
- Add unit test

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by dimak1** [comment]
@cameron-eyds @RuoxuanPengBC I pushed what I had. There is a smaller item left for Part 2 + unit tests, hopefully not a biggie.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1605-9ju60u8p.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by cameron-eyds — APPROVED** [review]

**Review by RuoxuanPengBC — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1605-cfyfkh09.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1605-cfyfkh09.web.app

**Pull request merged**
