### PR TITLE
PPR/MHR Registration Table Items

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#18923  /bcgov/entity#18925

*Description of changes:*
* Lots of minor adjustments (that are shared between both table instances) as listed in tickets.
* See ticket(s) for comprehensive list of items

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]
Nice improvements.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1674-rf2tns3v.web.app

**Review by doug-lovett — APPROVED** [review]
Looking good.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1674-rf2tns3v.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1674-rf2tns3v.web.app

**Comment by cameron-eyds** [comment]
Removed auto-select-first off the auto complete component. 
Was giving it a go, is a new feature introduced to improve accessibility but it seems a little touchy, maybe not quite ready.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1674-rf2tns3v.web.app

**Pull request merged**
