### PR TITLE
"Include lien info for all" state kept when navigating back from Summary page

### PR DESCRIPTION
**Pull request by garyfan1**
*Issue #:* /bcgov/entity#13383

*Description of changes:*
update checkbox behavior, add state to state model

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]

**Review by cameron-eyds — APPROVED** [review]
Code looks good!

If a user selects all and sets that to the app state, will it persist or does it reset on a new search? Was my only thought!

**Comment by garyfan1** [comment]
I thought it would retain, turns out it resets for some reason.

**Comment by cameron-eyds** [comment]
> I thought it would retain, turns out it resets for some reason.

Well i don't think you want it to persist to a new search criteria, however you do want it to persist between Select and Review pages. Is that correct?

**Comment by garyfan1** [comment]
Yes that is correct, and that's its behavior rn.

**Review by doug-lovett — APPROVED** [review]
Very nice Gary.

**Pull request merged**
