### PR TITLE
Non-Res-Exemption Unit Note Panel and Tests

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#17512

*Description of changes:*
- Include non res exemption info in Unit Note Panel Content
- Additional Unit Test

Screenshot 2024-04-24 at 6 49 33 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1845-pkqith6g.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1845-pkqith6g.web.app

**Pull request merged**
