### PR TITLE
Dealer Review Label

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#24171

*Description of changes:*
- Label Update

Screenshot 2024-11-20 at 11 51 53 AM
Screenshot 2024-11-20 at 11 51 48 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by flutistar — APPROVED** [review]
Looks good

**Review by doug-lovett — APPROVED** [review]
Sweet!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2069-56sk6azt.web.app

**Pull request merged**
