### PR TITLE
Dealer Requirements Acceptance

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#24273

*Description of changes:*
- Check if QS Dealer Record has accepted updated requirements
- Update if QS Dealer Record has accepted updated requirements
- Hide Dealer Content once requirements accepted

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2064-9ufhxk2e.web.app

**Review by flutistar — APPROVED** [review]
LGTM

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Pull request merged**
