### PR TITLE
Adds cancel dialog

### PR DESCRIPTION
**Pull request by orelbn**
*Issue #:* /bcgov/entity#17310

*Description of changes:*
- Shows cancel dialog in unit notes when the user presses the cancel button

image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1507-fkgmaze2.web.app

**Review by dimak1 — APPROVED** [review]

**Review by cameron-eyds — APPROVED** [review]
Spectacular

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1507-fkgmaze2.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1507-fkgmaze2.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1507-fkgmaze2.web.app

**Pull request merged**
