### PR TITLE
Expiry date fixes

### PR DESCRIPTION
**Pull request by orelbn**
*Issue #:* /bcgov/entity#16833

*Description of changes:*
- Fixes some minor issues with expiry date component
- Lets API set data when possible instead of trying to let data be set by UI

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
LGTM!

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1491-5u5olwn6.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
