### PR TITLE
Minor UXA for SJT Flow

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#18066

*Description of changes:*
* Some small font size and spacing updates as per uxa in listed ticket
* Global fix for text-field appended icon colour

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1697-a4nxlj8f.web.app

**Review by doug-lovett — APPROVED** [review]
LTGM. And it goes on and on and on...I like the golf analagy.

**Comment by cameron-eyds** [comment]
> LTGM. And it goes on and on and on...I like the golf analagy.

hahah indeed it does!

**Pull request merged**
