### PR TITLE
Fix general MHR Transfers issues

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#18950
- bcgov/entity#18927
- bcgov/entity#18930
- bcgov/entity#18937

*Description of changes:*
- Fix general MHR Transfers issues

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1671-4lpldij6.web.app

**Review by doug-lovett — APPROVED** [review]
LGTM

**Review by RuoxuanPengBC — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1671-4lpldij6.web.app

**Review by cameron-eyds — APPROVED** [review]
LG!

**Pull request merged**
