### PR TITLE
Drs-Mhr Table Integrations

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#23442

*Description of changes:*
- Integrates DRS with MHR - Feature Flagged
- Includes conditional Document ID column with direct link to document record edit service
- Sets up env variables and configurations

Screenshot 2024-10-18 at 7 53 47 AM

Screenshot 2024-10-18 at 7 53 53 AM

Screenshot 2024-10-18 at 7 54 02 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by flutistar — APPROVED** [review]
Amazing
🚀  🚀  🚀

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2042-tpk65hmy.web.app

**Pull request merged**
