### PR TITLE
Due to Death Transfers: Group Tenancy Typing

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#2264

*Description of changes:*
- Refactored latest fix to apply to all Transfer due to Death Scenarios except surviving joint tenancy
- @flutistar This was your fix, just applied to the other 2 Due to Death Transfers

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2022-7ouam3bl.web.app

**Review by doug-lovett — APPROVED** [review]
LG

**Review by flutistar — COMMENTED** [review]
LGTM

**Review by flutistar — APPROVED** [review]

**Pull request merged**
