### PR TITLE
Wysiwyg Styling Adjustments

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#16133

*Description of changes:*
* Minor styling adjustments to Wysiwyg and reviewable content

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1421-1d538tic.web.app

**Review by orelbn — APPROVED** [review]
Looks good!

**Review by dimak1 — APPROVED** [review]

**Comment by cameron-eyds** [comment]
Just a minor update with regards to the UX/QA part of the process.
I provided the preview URL to @chdivyareddy and the changes have been approved 👍

**Pull request merged**
