### PR TITLE
Declared Value Minimum 

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#20933

*Description of changes:*
- Validation on Declared value to prevent any variation of only zeros and/or mixed commas.

Screenshot 2024-06-11 at 7 37 30 AM
Screenshot 2024-06-11 at 7 37 26 AM
Screenshot 2024-06-11 at 7 37 20 AM
Screenshot 2024-06-11 at 7 37 15 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1932-j8ylelr4.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by dimak1 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1932-j8ylelr4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1932-j8ylelr4.web.app

**Pull request merged**
