### PR TITLE
Assets Node V Update

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#17598

*Description of changes:*
* Updates Node version to 20.5.1

Screenshot 2023-09-05 at 8 20 58 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1521-54pwrdgr.web.app

**Review by dimak1 — APPROVED** [review]

**Review by pwei1018 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1521-54pwrdgr.web.app

**Pull request merged**
