### PR TITLE
Bug fixes for Transfers (Sale or Gift, Suffix)

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#16396
- bcgov/entity#16348

*Description of changes:*
- Fix for two bugs in Transfers
- Rename props for consistency

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1347-muzsyide.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1347-muzsyide.web.app

**Review by cameron-eyds — APPROVED** [review]

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
