### PR TITLE
Updated QS Status Message Handling

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#16949

*Description of changes:*
* Implements close status messaging - stored in user settings misc preferences 
* Updates local property legal name -> authorization name

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1492-2q3qruqn.web.app

**Review by orelbn — APPROVED** [review]
LGTM!

**Review by doug-lovett — APPROVED** [review]
Marvellous

**Pull request merged**
