### PR TITLE
Trans Will flow validations

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* /bcgov/entity#15575

*Description of changes:*
- Validations for Will Transfer flow
- Update existing tests
- Add new tests

### Screenshots

Screen Shot 2023-04-11 at 5 53 50 PM

Screen Shot 2023-04-11 at 5 54 28 PM

Screen Shot 2023-04-11 at 5 55 17 PM

Screen Shot 2023-04-12 at 2 25 00 PM

Screen Shot 2023-04-12 at 2 24 27 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good to me, nice encapsulation on composable functions specific to Trans Will. 
That being said, the only thing to consider is maybe the name of that defined block. 
`TRANS_WILL` very much looks like a const/enum at surface level, especially when imported used. 
I can't think anything more concise however, perhaps we could brainstorm on that? 
Either way, maybe just using as camel case? `TransWill` seems less like a const/enum value?

**Comment by dimak1** [comment]
@cameron-eyds, thanks for the feedback. I was hoping you would bring that naming up, because I wasn't sure myself :) Will update it.

**Review by doug-lovett — APPROVED** [review]
LGTM.

**Comment by dimak1** [comment]
Hi @cameron-eyds could you pls review latest changes https://github.com/bcgov/ppr/pull/1262/commits/ddec15b30efee1bb830ffdcb60a55c35744faf68

**Review by cameron-eyds — APPROVED** [review]
LGTM!

**Pull request merged**
