### PR TITLE
Effective Date changes for Unit Notes

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17810

*Description of changes:*
- Remove time dropdown from Effective Date section of Unit Notes
- Refactor EffectiveDateTime component to become EffectiveDate
- Update Unit Note Panel and Review page

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1545-v4eseppr.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great, now I see why you asked if the API property name was changing.

**Comment by dimak1** [comment]
> Looks great, now I see why you asked if the API property name was changing.

Yea, everything got renamed so was thinking of cleaning up the payload prop. @doug-lovett

**Review by cameron-eyds — APPROVED** [review]
Looks good to me!

**Pull request merged**
