### PR TITLE
Add new create manufacturer info endpoint.

### PR DESCRIPTION
**Pull request by doug-lovett**
*Issue #:* /bcgov/entity#17063

*Description of changes:*
- Add POST /mhr/api/v1/manufacturers to support auth manufacturer account onboarding.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]
Looks good to me.

**Review by cameron-eyds — APPROVED** [review]
Looks great, thanks sir!

Side question, i believe we will need a GET as well for the qualified supplier information captured, is that something we've scoped out in another ticket?

**Comment by doug-lovett** [comment]
To confirm, the GET was already implemented and data for existing legacy manufacturers is available. We just need to link the BCRS account id's to the records when the accounts are created.

**Comment by cameron-eyds** [comment]
> To confirm, the GET was already implemented and data for existing legacy manufacturers is available. We just need to link the BCRS account id's to the records when the accounts are created.

Right on! Thank you sir

**Pull request merged**
