### PR TITLE
Mixed Roles Validations for Sale or Gift Transfers

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#15737

*Description of changes:*
- Validations errors for mixed roles types
- Home tenancy type update to N/A for mixed role types

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1312-yircwxg7.web.app

**Review by cameron-eyds — APPROVED** [review]
Looks good to me! 

Perhaps we wait until after Demo for merge however 👍

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1312-yircwxg7.web.app

**Pull request merged**
