### PR TITLE
A11Y-Table-UXA-Items

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#22055

*Description of changes:*
- Table UXA items for Search History and Home Owner Tables

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by flutistar — APPROVED** [review]
LGTM

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2023-8aeb0ayn.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
