### PR TITLE
Transfer Visual Validation Bug

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#20474

*Description of changes:*
- Clear validate on submission to prevent visual validation bug during the re-routing

 /bcgov/entity#20474 - Hide segmented menu and cancel permit option until further developmnet.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1823-k9aun7a7.web.app

**Review by dimak1 — APPROVED** [review]
LG!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1823-k9aun7a7.web.app

**Pull request merged**
