### PR TITLE
Fix unit tests + small cleanup

### PR DESCRIPTION
**Pull request by dimak1**
*Description of changes:*
- Fix MhrInformation unit tests after main branch sync
- Small formatting and cleanup

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good, thank you!

**Comment by dimak1** [comment]
@cameron-eyds It was really a line change, to set the new Land Lease radio (as you suspected). It fixed pretty much all tests because it is a required field now.

**Comment by cameron-eyds** [comment]
@dimak1 Nice! I'm glad it wasn't a hassle, thank you!
Regarding the console errors, perhaps some optional chaining would help on those?

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Comment by dimak1** [comment]
> @dimak1 Nice! I'm glad it wasn't a hassle, thank you! Regarding the console errors, perhaps some optional chaining would help on those?

@cameron-eyds I didn't get any console errors in my local dev env. Should we look into it now or later?

**Comment by cameron-eyds** [comment]
@dimak1 I didn't see them locally either, just in the CD Logs. 
Pretty small, maybe try optional chaining `document`? 
Either way, not a blocker! 

Screenshot 2023-12-04 at 4 19 42 PM

**Pull request merged**
