### PR TITLE
Updates for Affidavit Transfers

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#15639

*Description of changes:*
- Validations updates
- Various fixes including styling fixes
- Error messages to use resources file
- Add tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1294-fwol3pm6.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1294-fwol3pm6.web.app

**Review by cameron-eyds — APPROVED** [review]
Looks good! 👍

**Review by doug-lovett — APPROVED** [review]
LGTM.

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1294-fwol3pm6.web.app

**Pull request merged**
