### PR TITLE
Locked QS Flows

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Description of changes:*
*Issue #:* /bcgov/entity#15848
- Display Locked badge for QS when MHR is frozen due to affi
- Include disabled states and prevent pre-populated SOG Transfer flow (for QS)

*Issue #:* /bcgov/entity#15848
- Bug fix for setting business partyType
- Include net-new validation to prevent action on HomeOwner groups in Death Transfers when the Whole Group/SO/JT are all businesses. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1813-if32y1pz.web.app

**Comment by cameron-eyds** [comment]
Not sure what is up with the codecov servers, but failing to upload today!
Tests are passing, just the upload is failing 👎 Maybe we need to generate a new codecov token?

Screenshot 2024-04-08 at 3 15 54 PM

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1813-if32y1pz.web.app

**Review by dimak1 — APPROVED** [review]
Looks good to me.

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Pull request merged**
