### PR TITLE
Declaration Details

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#17510

*Description of changes:*
- Declaration Details Component for non-res exemption
- Minor exemption setup to allow to component testability (more to come here in framework ticket)
- Unit tests and feature flag implementation (Arlen is creating in LD)
- Minor transfer uxa validation update

Screenshot 2024-04-15 at 10 59 17 AM

Screenshot 2024-04-15 at 10 59 30 AM

Screenshot 2024-04-15 at 10 59 34 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1827-6cn34wu8.web.app

**Review by dimak1 — COMMENTED** [review]
Nice, looks great, thanks for screenshots, it helped.

**Review by dimak1 — APPROVED** [review]

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1827-6cn34wu8.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1827-6cn34wu8.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1827-6cn34wu8.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1827-6cn34wu8.web.app

**Pull request merged**
