### PR TITLE
Transfers: Stale Draft Dialog and Removal

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#15820

*Description of changes:*
* Prompt User when trying to resume a stale draft(transfers) as flagged by the api using the `outOfDate` flag. 
* Delete draft is prompted.

Screenshot 2024-01-30 at 2 03 27 PM

Screenshot 2024-01-30 at 2 06 17 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1712-kdxsfmkn.web.app

**Review by dimak1 — APPROVED** [review]
Nice, thanks for the tests.

**Review by doug-lovett — APPROVED** [review]
Looks grand.

**Pull request merged**
