### PR TITLE
Fix error state for Groups in Transfers

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#16290
- bcgov/entity#16292

*Description of changes:*
- UXA feedback to hide error state for Groups for LETA and WILL Transfers

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Review by doug-lovett — APPROVED** [review]
LGTM.

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1364-2wmnvotn.web.app

**Pull request merged**
