### PR TITLE
QS: Transfer Unit Testing

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#16039

*Description of changes:*
- Additional unit testing to test scenarios described in ticket
- Test suite iterates through QS types, with some QS testing variance inside test scope.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1951-9gnrv25e.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1951-9gnrv25e.web.app

**Pull request merged**
