### PR TITLE
18373 unit notes person giving notice

### PR DESCRIPTION
**Pull request by flutistar**
*Issue #:* /bcgov/entity#18373

*Description of changes:*
Make `attention` field as empty when the note is redemption note.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1988-t3o6yg15.web.app

**Review by cameron-eyds — APPROVED** [review]
Lgtm!

*Before you start the next task/ticket we should review your GH workflow.

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
