### PR TITLE
Fix Multiple Issues with Home Owner Groups

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17650

*Description of changes:*
- Fix validations, error states for Home Owner groups 
- Support fixes with unit tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1575-ebo3myhp.web.app

**Review by doug-lovett — APPROVED** [review]
Transfers go on and on and on.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1575-ebo3myhp.web.app

**Review by cameron-eyds — APPROVED** [review]
Loooks great 👍

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1575-ebo3myhp.web.app

**Pull request merged**
