### PR TITLE
Mhr History Owners

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* 

*Description of changes:*
/bcgov/entity#21927
- Mhr History for Home Owners
- Unit tests
- Added some display value formatting

Screenshot 2024-07-08 at 10 21 16 AM

Screenshot 2024-07-08 at 10 21 24 AM

/bcgov/entity#22140
- Update to adapt UI to preserved owner group orders following Transfers
- Includes the logic update that auto-adds to the appropriate owner group

Screenshot 2024-07-08 at 10 19 47 AM

Screenshot 2024-07-08 at 10 20 01 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1968-f1bhy5uy.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Review by dimak1 — APPROVED** [review]
Looks great, nice work!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1968-f1bhy5uy.web.app

**Pull request merged**
