### PR TITLE
MHR: Unsaved Changes Handler

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#12542

*Description of changes:*
* Implements the handlers for unsaved changes on navigation in the MHR
* Validation Reset in MHR Wrapper

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by ChasBoucher — APPROVED** [review]
Looks Good..

**Review by dimak1 — APPROVED** [review]
Looks good, just two things:
- Saved / Unsaved changes were a bit confusing, as we don't really have a save functionality. Then I read the task, and I guess we can follow the requirement wording.
- Tasks mentions there should be a modal when user is trying to exit prematurely. Is that still coming?

**Comment by cameron-eyds** [comment]
> Looks good, just two things:
> 
> * Saved / Unsaved changes were a bit confusing, as we don't really have a save functionality. Then I read the task, and I guess we can follow the requirement wording.
> * Tasks mentions there should be a modal when user is trying to exit prematurely. Is that still coming?

@dimak1 Agreed, we are not exactly saving are we 😁 But yes, as per requirements it was put in. 
You bet, the dialog is already in, it is a pre-existing one.

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
