### PR TITLE
PPR API  API DB Healthcheck

### PR DESCRIPTION
**Pull request by doug-lovett**
Signed-off-by: Doug Lovett <doug@diamante.ca>

*Issue #:* /bcgov/entity###

*Description of changes:*
Add /ops/healthz db connection health check.
Disable schema validation for drafts to allow incomplete saves.
Turn off debug db connection logging.
Include CROWNLIEN registration class in financing statement queries.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by thorwolpert — CHANGES_REQUESTED** [review]
This has a lot of stuff that is not related to the OPs end-point.
The ope end-point is missing the mount here as well
https://github.com/bcgov/ppr/blob/main/ppr-api/src/ppr_api/resources/__init__.py#L69

**Comment by doug-lovett** [comment]
The OPS mount config is on line 58 and has a different base path.
And you are right the PR has more than just the heartbeat change. It is cumulative because of the lag on reviewing PR's. Case in point: I just added 7340 changes which I completed after opening this PR. And I already have UI changes for another PR  ready to go.

**Comment by thorwolpert** [comment]
so can we split this into the ops end point, and what ever the other stuff is?

**Comment by doug-lovett** [comment]
Close this PR and open 2 new ones?

**Pull request closed without merging**
