### PR TITLE
DRS Configurations and Minor Text Updates

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#23442

*Description of changes:*
- Add DRS configs to the vaults
- Minor text content updates as per QA
- Fixes QS Dealer/MF name match condition bug

Screenshot 2024-10-22 at 12 28 31 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2044-4xm7tw08.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2044-4xm7tw08.web.app

**Pull request merged**
