### PR TITLE
9140 general collateral for confirmation page

### PR DESCRIPTION
**Pull request by jordiwes**
*Issue #:* /bcgov/entity#9140

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by doug-lovett — APPROVED** [review]
LGTM

**Review by kialj876 — CHANGES_REQUESTED** [review]
again, looks good to me but tests are failing :(

**Comment by jordiwes** [comment]
it's been a ride to merge everything together... should be fixed now

**Review by kialj876 — APPROVED** [review]
Looks good!

**Pull request merged**
