### PR TITLE
Crown charge user lien items

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#18916

*Description of changes:*
* Fixes to crown charger user auto-complete secured parties
* Fixes to local date pick (in process of updated shared component for re-import)
* fixes to Transfer flows
- Includes: Type change handling and select, styling and display

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1656-9mkh8y4p.web.app

**Review by RuoxuanPengBC — APPROVED** [review]
Looks great!

**Review by doug-lovett — APPROVED** [review]
Nice one.

**Pull request merged**
