### PR TITLE
UXA Updates and Draft Verification

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#24441

*Description of changes:*
- Minor UXA and Draft Verification

Screenshot 2024-11-26 at 6 00 39 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2075-lc0huxf8.web.app

**Review by doug-lovett — APPROVED** [review]
Spectacular!

**Review by flutistar — APPROVED** [review]
Looks good

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2075-lc0huxf8.web.app

**Pull request merged**
