### PR TITLE
Vue 3 - Feature Branch Fold In

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#16983

*Description of changes:*
- Pr for folding in feature branch back into our main branch

*Includes*
- Vue 3 upgrade
- Vuetify upgrade
- Vite migration
- Vitest migration
- Removal of many previously use technologies, such as Jest, webpack and many unsupported component packages

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1642-gnlazust.web.app

**Review by dimak1 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1642-gnlazust.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1642-gnlazust.web.app

**Review by doug-lovett — APPROVED** [review]
Wow, what an amazing amount of work. I skipped the unit tests and scanned most of the rest. Fantastic work.

**Comment by cameron-eyds** [comment]
> Wow, what an amazing amount of work. I skipped the unit tests and scanned most of the rest. Fantastic work.

Thank you! It was for sure, a huge collaboration between a lot of folks. Our team and others.
Still some fine tuning to go but getting closer everyday.

**Pull request merged**
