### PR TITLE
Update Giving Notice Party title for TAXN note

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17128

*Description of changes:*
- Update title to Collector

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1501-efv1y209.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Review by orelbn — APPROVED** [review]
Looks great!

**Pull request merged**
