### PR TITLE
Declared Value Commas

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#20616

*Description of changes:*
- Allow commas in declared value / Cast to int and remove on submission
- Additional validation message for Death Transfers when no persons exist in any owner group

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1815-yot5b76d.web.app

**Review by dimak1 — APPROVED** [review]
LG!

**Review by doug-lovett — APPROVED** [review]
Nice.

**Pull request merged**
