### PR TITLE
Unit Note Panels UX

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#16505

*Description of changes:*
* Changed some font sizes
* Capped Panels height
* Maintain only 1 panel open at a time.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1384-qqbd2n5o.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great again!

**Review by orelbn — APPROVED** [review]
Looks great!

**Pull request merged**
