### PR TITLE
Securities Act Notice outputs, discharge registration.

### PR DESCRIPTION
**Pull request by doug-lovett**
*Issue #:* /bcgov/entity#21191

*Description of changes:*
- PPR API Securities Act registration, search output updates from UX design.
- Example outputs attached to the ticket.
- 15192 part 1 Securities Act Notice Discharges and verification outputs.
- Add user profile property "hasSecuritiesActAccess" to GET /mhr/api/v1/user-profile response.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]
LG!

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by doug-lovett** [comment]
@cameron-eyds I added user profile property "hasSecuritiesActAccess" to the GET /mhr/api/v1/user-profile response in this PR.

**Comment by cameron-eyds** [comment]
> @cameron-eyds I added user profile property "hasSecuritiesActAccess" to the GET /mhr/api/v1/user-profile response in this PR.

@doug-lovett Awesome, thank you sir. Will implement!
Sorry to ask again, which account(s) will this be added to again, in Dev/Test?

**Pull request merged**
