### PR TITLE
SAN Court Orders

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#21106

*Description of changes:*
- Build out SAN Court Order form  and Review Component to current designs (includes validations)
- Integrate SAN Court Orders into Notices Model and Panels components
- Notice type property name update to meet api specs
- Unit Tests

Screenshot 2024-05-16 at 11 07 12 AM

Screenshot 2024-05-16 at 11 07 58 AM

Screenshot 2024-05-16 at 11 07 50 AM

Screenshot 2024-05-16 at 11 07 39 AM

Screenshot 2024-05-16 at 11 07 22 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1879-1093frgd.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by cameron-eyds** [comment]
I think Dima is off until Tuesday, so will merge today to hand over to UXA.

**Pull request merged**
