### PR TITLE
Use sbc-common-components v4.0.7

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#18903

*Description of changes:*
- Upgrade sbc-common-components which fixes the Registries Account Login page 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1952-go9it72q.web.app

**Review by cameron-eyds — APPROVED** [review]

**Review by doug-lovett — APPROVED** [review]

**Comment by dimak1** [comment]
Hey @cameron-eyds, in preview link, the hero image is not showing up (broken url). However in local dev, it it's here. I'm trying to investigate, so if you have some ideas, please let me know. Thanks!

**Comment by cameron-eyds** [comment]
> Hey @cameron-eyds, in preview link, the hero image is not showing up (broken url). However in local dev, it it's here. I'm trying to investigate, so if you have some ideas, please let me know. Thanks!

Will have a look!

**Comment by cameron-eyds** [comment]
@dimak1 
It looks like a potential issue with the src path in the common component. As is, it's looking for the asset with a relative path and while this may be an accurate path in our local builds, a vite production build will (probably) differ. I would recommend going with an alias path for the static assets, so it's always pulling from the same place regardless of build.

If you want to test this locally you can as well, in your terminal `npm run build` to create a production build and `npm run preview` to then view it in the browser. 

So, to get this to work you may need to do a few things, update the common component path:
Screenshot 2024-06-26 at 10 45 57 AM

*edit: you can also alias back to sbc if you would prefer to not store the image locally
ie `@sbc/` That should work as well

Also, if we want to use the v-img, we will need a small configuration update in our project. Vite-Vuetify preset can transform the aliased paths. ie in our Vite config:

Screenshot 2024-06-26 at 10 45 32 AM

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1952-go9it72q.web.app

**Pull request merged**
