### PR TITLE
Updates for Unit Note submission

### PR DESCRIPTION
**Pull request by dimak1**
*Description of changes:*
- Small fixes for Unit Notes on Chrome
- Unsaved changes dialog is showing up on Chrome, so this should fix that.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks great!

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1449-pkgzip50.web.app

**Review by doug-lovett — APPROVED** [review]

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1449-pkgzip50.web.app

**Pull request merged**
