### PR TITLE
Fix Frozen Transfers flow and reset Doc Id

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17644

*Description of changes:*
- Fix Frozen Transfers flow for Sale or Gift after Affidavit Transfer
- UXA feedback: Reset Document Id for Sale or Gift after Affidavit Transfer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1554-j9fipo81.web.app

**Review by RuoxuanPengBC — APPROVED** [review]
Looks good to me

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Pull request merged**
