### PR TITLE
13809 ppr search result displaying selection list

### PR DESCRIPTION
**Pull request by flutistar**
*Issue #:* /bcgov/entity#13809

*Description of changes:*
 * Added `tombstoneBreadcrumbMhrSearch` for `MHR Search`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]
LGTM!

**Comment by dimak1** [comment]
Hi @flutistar, I noticed there are merge commits. We normally sync via `rebase`. Here is a example/workflow: https://github.com/bcgov/namex/blob/main/docs/developer.md
Screenshot 2024-07-17 at 11 37 59

**Comment by flutistar** [comment]
Thanks @dimak1 
I will keep that in my mind.

**Review by cameron-eyds — COMMENTED** [review]
Code changes look good but you'll need to make a small update to the unit tests!

**Comment by flutistar** [comment]
I got you @cameron-eyds

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1985-nyr1xfz3.web.app

**Pull request merged**
