### PR TITLE
Move Completed: Create New Transport Permit

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#21477

*Description of changes:*
- Expand Transport Permit Flows to include new Transport Permit when Active permit has completed its move 
- Includes changes from Dealer Permission Hotfix #23704

Screenshot 2024-10-10 at 3 52 18 PM

Screenshot 2024-10-10 at 3 52 24 PM

Screenshot 2024-10-10 at 3 52 36 PM

Screenshot 2024-10-10 at 3 52 56 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2036-jrn3xea5.web.app

**Review by doug-lovett — APPROVED** [review]
Beautiful!

**Review by flutistar — APPROVED** [review]
LGTM

**Pull request merged**
