### PR TITLE
Puba Table Labels

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#20061

*Description of changes:*
* Updates Correct and Corrected Labels to dynamic Amend and Amended for PUBA
* Updates in Home Sections and MHR Home Owners for Corrections/Amendments
* Updated Unit Testing

Screenshot 2024-04-01 at 7 02 41 AM
Screenshot 2024-04-01 at 7 02 01 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1805-br8cdngi.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by cameron-eyds** [comment]
> Looks great.

Thank you!

**Pull request merged**
