### PR TITLE
Add Accessible Semantics

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#21286

*Description of changes:*
- Update a11y semantics: Dashboard, Mhr Info, Review, Transport Permit

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1970-vdfzyya8.web.app

**Comment by cameron-eyds** [comment]
After a quick look i think we might need to discuss.

This PR implies a re-write/replacement of the Vuetify grid system.. the implications are quite large when talking about doing this app-wide. 

I know Vuetify has it's challenges but it certainly helps us keep standarized within our application and the others that use it.
Moving away from this and to custom created classes, i'm not so sure about.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1970-vdfzyya8.web.app

**Comment by dimak1** [comment]
After a discussion with @cameron-eyds, I will make the updates.

**Review by cameron-eyds — APPROVED** [review]
Looks good! 

It can be done whenever, but is it possible to add some notes/tracking/context to the A11Y ticket itself. I think other teams are going to look at some of these tickets following our work and any context on the why or what will help everyone!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1970-vdfzyya8.web.app

**Review by doug-lovett — APPROVED** [review]
Very nice.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1970-vdfzyya8.web.app

**Pull request merged**
