### PR TITLE
Lien/Locked Update

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#17700

*Description of changes:*
- Update lien/locked so that locked will take precedence over lien badge.
- Restored Token Refresh function

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1653-gg5hxn20.web.app

**Review by doug-lovett — APPROVED** [review]
Looking good.

**Review by RuoxuanPengBC — APPROVED** [review]
Looks great!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1653-gg5hxn20.web.app

**Pull request merged**
