### PR TITLE
Validations updates for Transfers to Admin (LETA)

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#15808

*Description of changes:*
- Fix validations + UXA items for LETA Transfers

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1335-8jb7o9fi.web.app

**Review by cameron-eyds — APPROVED** [review]
LG!

**Review by orelbn — APPROVED** [review]
LG!

**Pull request merged**
