### PR TITLE
UI - Extend Transport Permits

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#23540

*Description of changes:*
- Modifies existing flows for Transport Permits to allow for Permit Extension

Screenshot 2024-10-08 at 12 02 41 PM

Screenshot 2024-10-08 at 12 02 54 PM

Screenshot 2024-10-08 at 12 03 09 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2032-81szhmm0.web.app

**Review by flutistar — APPROVED** [review]
LGTM

**Review by doug-lovett — APPROVED** [review]
Outstanding!

**Pull request merged**
