### PR TITLE
Fixes for Location Type Change in Transport Permit

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#20182

*Description of changes:*

Fixes for Location Type Change:
- Clear fields when selecting location type
- Fix to preserve previous selection to correctly show confirm modal

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1774-aolzynqw.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1774-aolzynqw.web.app

**Review by cameron-eyds — APPROVED** [review]
LGTM!

**Review by doug-lovett — APPROVED** [review]
LG.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1774-aolzynqw.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1774-aolzynqw.web.app

**Pull request merged**
