### PR TITLE
MHR API add reg summary lienRegistrationType

### PR DESCRIPTION
**Pull request by doug-lovett**
Signed-off-by: Doug Lovett <doug@diamante.ca>

*Issue #:* /bcgov/entity#14330

*Description of changes:*
Add lienRegistration to API get account summary registration info for MHR.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Review by dimak1 — APPROVED** [review]

**Comment by cameron-eyds** [comment]
Just a follow up Q: Does the type of `lienRegistrationType` matter with regards to UI or is it just a condition if this property is `truthy`, we know we there is an active lien. 

From the design, it doesn't really indicate types, just that one exists. So i'm assuming the presence of a type here would suffice for the UI.

**Comment by doug-lovett** [comment]
PPR lien registration type may matter for some MHR registrations. A non-empty value is equivalent to an existence check. There may be some future registrations that can complete base on the registration type.

**Comment by cameron-eyds** [comment]
> PPR lien registration type may matter for some MHR registrations. A non-empty value is equivalent to an existence check. There may be some future registrations that can complete base on the registration type.

Excellent, sounds good. Thanks for the info!

**Pull request merged**
