### PR TITLE
Changes to add commas between multiple owner names

### PR DESCRIPTION
**Pull request by owillborn**
*Issue #:* /bcgov/entity#15627

*Description of changes:*
- Fix to add commas between owner names on MHR Table in dashboard

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by dimak1** [comment]
@owillborn I thought this was a UI change?

**Comment by owillborn** [comment]
> @owillborn I thought this was a UI change?

@dimak1 The string already gets formatted here then passed to the UI, so my idea was to do all the formatting in one go. Can refactor to do this in the UI if its a problem

**Comment by dimak1** [comment]
@owillborn ok I see. Do you know if this affects reports then?

**Comment by owillborn** [comment]
> @owillborn ok I see. Do you know if this affects reports then?

@dimak1 Not as far as I can see. There's some formatting here with newlines which are reflected in the table but not in the reports, the commas are behaving the same

**Review by dimak1 — APPROVED** [review]

**Review by doug-lovett — APPROVED** [review]
LGTM.

**Review by cameron-eyds — APPROVED** [review]
Simply amazing

**Pull request merged**
