### PR TITLE
Mhr History Feedback items

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#18147

*Description of changes:*
- Change displayed Tombstone
- Minor table cell alignments

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]

**Review by doug-lovett — APPROVED** [review]
Working hard or hardly working.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1974-883t2sq4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1974-883t2sq4.web.app

**Pull request merged**
