### PR TITLE
Add ownerStatus to MHR api search summary response.

### PR DESCRIPTION
**Pull request by doug-lovett**
Signed-off-by: Doug Lovett <doug@diamante.ca>

*Issue #:* /bcgov/entity#12830

*Description of changes:*
- Add ownerStatus to MHR api search summary response.
- Add status to owner information in search registration data.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good! 👍

**Comment by cameron-eyds** [comment]
@doug-lovett 
Looks great!
Will this require a subsequent design/UI change to follow up?

**Comment by doug-lovett** [comment]
@cameron-freshworks Yes, there will be a separate ticket - we discussed it in the status meeting before you joined. The possible owner status values are ACTIVE, EXEMPT, PREVIOUS.

**Comment by cameron-eyds** [comment]
> @cameron-freshworks Yes, there will be a separate ticket - we discussed it in the status meeting before you joined. The possible owner status values are ACTIVE, EXEMPT, PREVIOUS.

Sounds good, thanks!

**Review by dimak1 — APPROVED** [review]

**Pull request merged**
