### PR TITLE
Add GET manufacturer info endpoint

### PR DESCRIPTION
**Pull request by doug-lovett**
*Issue #:* /bcgov/entity#16418

*Description of changes:*
Add mhr_manufacturers table and GET endpoint to fetch manufacturer information to support new MH registrations for manufacturers.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1351-shdd01ce.web.app

**Review by orelbn — APPROVED** [review]
Awesome job!

**Review by dimak1 — APPROVED** [review]

**Review by cameron-eyds — APPROVED** [review]
Looks grrrrrrrrrreat 🐯

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1351-shdd01ce.web.app

**Pull request merged**
