### PR TITLE
Unit Notes UXA feedback + validation update 

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#16517
- bcgov/entity#16509

*Description of changes:*
- Update styling for Unit Notes and related components
- Add Combine Name Validation for Person Giving Notice
- See screenshots below

Screenshot 2023-06-28 at 11 33 57 AM

Screenshot 2023-06-28 at 2 55 59 PM

Screenshot 2023-06-28 at 3 01 40 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by orelbn — APPROVED** [review]
Looks great!

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1403-al1oviv0.web.app

**Review by doug-lovett — APPROVED** [review]

**Review by cameron-eyds — APPROVED** [review]
Looks good 👍

**Pull request merged**
