### PR TITLE
Fix Land Lease validation for draft MHR Registrations

### PR DESCRIPTION
**Pull request by dimak1**
*Description of changes:*
- Fix Land Lease validation for draft MHR Registrations

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by cameron-eyds — APPROVED** [review]
Looks great,
After you merge, we will promote straight to TEST, so we can get our feature back to Dev 👍 
Just keep me posted!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1647-zjvclufs.web.app

**Review by RuoxuanPengBC — APPROVED** [review]
Looks great

**Comment by cameron-eyds** [comment]
Closing as a fix was applied in PR: https://github.com/bcgov/ppr/pull/1659 and released as a hotfix.
Have also committed the fix to our main branch 👍

**Pull request closed without merging**
