### PR TITLE
Secured Party Fixes

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#18919

*Description of changes:*
- Update validations for secured parties - don't include removed secured parties in general user amendment scenarios.
- Fixed Duplicate secured parties dialog btn styling

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1665-oq8fizk1.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1665-oq8fizk1.web.app

**Review by doug-lovett — APPROVED** [review]
Outstanding.

**Pull request merged**
