### PR TITLE
Table A11Y Updates

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#22058

*Description of changes:*
- Minor updates to various Tables listed in ticket to provide a better screen reader experience
- Developed with MacVoiceOver using Safari Browser

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2025-iwowpxzo.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Review by flutistar — APPROVED** [review]
LGTM

**Pull request merged**
