### PR TITLE
Search results return activeCount, exemptCount, historicalCount for o…

### PR DESCRIPTION
**Pull request by doug-lovett**
…wner status.

Signed-off-by: Doug Lovett <doug@diamante.ca>

*Issue #:* /bcgov/entity#15061

*Description of changes:*
- Collapse search results with identical names within a MH registration. 
- Also refactor search results to facilitate transition from DB2 to Postgres
- Also align search report regeneration with registration report regeneration. 
- 14095 only display NCON, 102 document type remarks for staff.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]

**Comment by dimak1** [comment]
Hi @doug-lovett, which API endpoints got updated? Is schema going to be updated as well? Thanks

**Review by owillborn — APPROVED** [review]
Looks good

**Review by ChasBoucher — APPROVED** [review]
Looks good..

**Comment by doug-lovett** [comment]
@dimak1 yes, https://bcregistry-demo.apigee.io/docs/mhrproxy/1/overview has been updated, including the searchSummaryInformation schema definition. So the POST /mhr/api/v1/searches response has been updated.

**Pull request merged**
