### PR TITLE
Lien Type Blocking Validation

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#22792

*Description of changes:*
- A fix was put in to unblock access to the Transfer/Permits/Exemptions etc but there was downstream validations blocking the user from proceeding. This fix is correct that validation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by flutistar — APPROVED** [review]
LGTM

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2006-tp9st3y6.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
