### PR TITLE
Remove secured party dialog modal for registering party

### PR DESCRIPTION
**Pull request by orelbn**
*Issue #:* /bcgov/entity#16097

*Description of changes:*
- No longer shows the secured party dialog modal when adding or changing a registering party.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1433-kw1rczb2.web.app

**Review by dimak1 — APPROVED** [review]

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1433-kw1rczb2.web.app

**Review by cameron-eyds — APPROVED** [review]
LGTM!

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
