### PR TITLE
Transfer To Administrator (LETA) initial

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#15807

*Description of changes:*
- Text updates for LETA Transfers
- Unit tests

Screen Shot 2023-05-04 at 11 34 52 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1316-q4eo2p97.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by cameron-eyds — APPROVED** [review]
Looks good!

Will need to get this in sooner than later to avoid conflicts in my current work :)
Is there more commits to come on this branch?

**Review by orelbn — APPROVED** [review]
Looks good to me!

**Pull request merged**
