### PR TITLE
Fixes for MHR Transfers

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17644

*Description of changes:*
- Fixes for various Transfer issues

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by doug-lovett — APPROVED** [review]
looks good

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1562-bhwria77.web.app

**Review by cameron-eyds — APPROVED** [review]
LGTM!

**Pull request merged**
