### PR TITLE
Update Transfer Type selector based on Roles

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#15886

*Description of changes:*
- Fix the Transfer Type dropdown items for Qualified Supplier

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1541-j55z5h1i.web.app

**Review by doug-lovett — APPROVED** [review]
LGTM

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1541-j55z5h1i.web.app

**Pull request merged**
