### PR TITLE
Transport Permit, Amend and Cancel: Folio Payload

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#23055

*Description of changes:*
- includes Folio in payloads for Amend, Cancel, and Permit payloads conditionally

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by flutistar — APPROVED** [review]
LGTM

**Review by doug-lovett — APPROVED** [review]
Fast work, very nice.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2017-uyc9vi68.web.app

**Pull request merged**
