### PR TITLE
Tax Cert: CheckOptions and Help Content

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#23025

*Description of changes:*
- Adds help content for Tax certificate
- Staff and Qs Help Content
- Staff only: Checkbox to disable the requirement for Tax Certification.

Screenshot 2024-10-16 at 12 17 25 PM

Screenshot 2024-10-16 at 12 17 34 PM

Screenshot 2024-10-16 at 12 23 34 PM

Screenshot 2024-10-16 at 12 23 43 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2040-1fcglt9x.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2040-1fcglt9x.web.app

**Review by flutistar — APPROVED** [review]
Looks good

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-2040-1fcglt9x.web.app

**Pull request merged**
