### PR TITLE
MHR API replace HISTORICAL MH status with CANCELLED.

### PR DESCRIPTION
**Pull request by doug-lovett**
*Issue #:* /bcgov/entity#17033

*Description of changes:*
- MHR API replace HISTORICAL MH status with CANCELLED. Search report example attached to issue.
- 17030 fix for modernized registration data check not always working with a timestamp comparison. Compare document ID's instead.
- 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by orelbn — APPROVED** [review]
Looks great!

**Review by cameron-eyds — APPROVED** [review]
Looks great! 
Is the intention to replace all instances of HISTORICAL with CANCELLED in the UI as well?

It looks like the UI supports `CANCELLED ` currently but we may have some updates following.

**Review by dimak1 — APPROVED** [review]

**Comment by orelbn** [comment]
> Looks great! Is the intention to replace all instances of HISTORICAL with CANCELLED in the UI as well?
> 
> It looks like the UI supports `CANCELLED ` currently but we may have some updates following.

@cameron-eyds 
I believe we groomed one API and one UI ticket last week when you were away. Ill update with the ticket number shortly.

UPDATE TICKET:

https://app.zenhub.com/workspaces/assets-team-space-61426544e7e2ea001d079597/issues/gh/bcgov/entity/17031

**Comment by cameron-eyds** [comment]
> > Looks great! Is the intention to replace all instances of HISTORICAL with CANCELLED in the UI as well?
> > It looks like the UI supports `CANCELLED ` currently but we may have some updates following.
> 
> @cameron-eyds I believe we groomed one API and one UI ticket last week when you were away. Ill update with the ticket number shortly.
> 
> UPDATE TICKET:
> 
> https://app.zenhub.com/workspaces/assets-team-space-61426544e7e2ea001d079597/issues/gh/bcgov/entity/17031

Excellent, thank you!

**Pull request merged**
