### PR TITLE
13931 Add validate-on-blur to base address

### PR DESCRIPTION
**Pull request by ChasBoucher**
*Issue #:* /bcgov/entity#13931
*Description of changes:*

- Add validate-on-blur to country autocomplete field to ensure proper country is selected for Canada Post validation and Address selection.
- Tested on ppr as well.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Lgtm

**Comment by dimak1** [comment]
@ChasBoucher the ticket AC mentions only Registration flow but the PR change affects all instances of BaseAddress. This can be an issue, as we incorrectly fulfilling the requirement. Not to be picky but the correct way is to either update the AC (to validate all addresses on blur) or to have it only done for MHR flow.

**Comment by cameron-eyds** [comment]
> @ChasBoucher the ticket AC mentions only Registration flow but the PR change affects all instances of BaseAddress. This can be an issue, as we incorrectly fulfilling the requirement. Not to be picky but the correct way is to either update the AC (to validate all addresses on blur) or to have it only done for MHR flow.

Dima is spot on here!
Please confirm with design that this is acceptable/expected for all instances of the address component.

**Review by doug-lovett — APPROVED** [review]

**Comment by cameron-eyds** [comment]
@ChasBoucher Please advice when you have confirmed with Design regarding this change affecting ALL instances of the Base Address component, thanks!

**Comment by ChasBoucher** [comment]
@dimak1 @cameron-eyds  I put the question out to the team in the ticket... Valid point.... 

The reason why I made the change to BaseAddress, is because, it is a bug that also exists in PPR(not reported)... I did test..

**Comment by cameron-eyds** [comment]
> @dimak1 @cameron-eyds I put the question out to the team in the ticket... Valid point....
> 
> The reason why I made the change to BaseAddress, is because, it is a bug that also exists in PPR(not reported)... I did test..

Sounds good, thank you! Keep us posted

**Review by dimak1 — CHANGES_REQUESTED** [review]
QA raised concerns as well. Pending AC review. Marking it as 'Request Changes'.

**Comment by ChasBoucher** [comment]
Ok..

**Comment by ChasBoucher** [comment]
@dimak1 I think we can move forward on this one.  Ticket has been updated.

**Comment by dimak1** [comment]
@ChasBoucher Divya didn't get a chance to test if there are any impact/issues for PPR. She said she will contact you tomorrow.

**Comment by ChasBoucher** [comment]
Had a very good meeting with Divya regarding change... I did explain that the fix will affect PPR and will need to be tested.

In the process we found one of the issues was not addressed and will most likely require another modification to the BaseAddress.

**Comment by cameron-eyds** [comment]
> Had a very good meeting with Divya regarding change... I did explain that the fix will affect PPR and will need to be tested.
> 
> In the process we found one of the issues was not addressed and will most likely require another modification to the BaseAddress.

Sounds good, thanks Charles. Is that change coming in this PR or a follow up?
Is this PR good to go?

**Comment by dimak1** [comment]
@ChasBoucher thanks for confirming. Divya said there is another fix that will be part of this PR. So we'll wait for that. @cameron-eyds

**Comment by cameron-eyds** [comment]
> @ChasBoucher thanks for confirming. Divya said there is another fix that will be part of this PR. So we'll wait for that. @cameron-eyds

Sounds good, thanks!

**Comment by ChasBoucher** [comment]
Closing because of the old issue of not merging correct... Only  small changes...

**Pull request closed without merging**
