### PR TITLE
Fix Location Type payload and PidNumber refactor

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#18317

*Description of changes:*
- Payload fix for Location Type
- PidNumber refactor

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good 👍

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1722-04h6m79v.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Pull request merged**
