### PR TITLE
Expiry Date Display Formatting

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#18443

*Description of changes:*
- Updated expiry date display 'N/A' condition to include `9999` days 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1948-1m0t6fvw.web.app

**Review by doug-lovett — APPROVED** [review]
Another tough one.

**Comment by cameron-eyds** [comment]
> Another tough one.

haha indeed!

**Pull request merged**
