### PR TITLE
Add expand transition for Optional Contact Info

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#17584

*Description of changes:*
- Add a smooth transition when show/hide the Optional Person Giving Notice.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by dimak1** [comment]
Note to reviewers. Easier if Unified view is turned on and white space hidden.

Screenshot 2023-09-15 at 1 15 19 PM

**Review by doug-lovett — APPROVED** [review]

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1535-x6skarxj.web.app

**Pull request merged**
