### PR TITLE
Updates to Additional Name for Admin Transfers

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#15808

*Description of changes:*
- Updates to Additional Name for Admin Transfers (to show Administrator text in suffix)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1339-gccqq9ec.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1339-gccqq9ec.web.app

**Review by orelbn — APPROVED** [review]
LGTM!

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by cameron-eyds — APPROVED** [review]
Looks good to me!

**Pull request merged**
