### PR TITLE
Vue2.7 Fold In

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#16393

*Description of changes:*
* As per last PR - Upgrade Vue, Pinia and other Misc packages
* Refactors to components, store and tests to support package changes

*Notes:*
- This branch is synced with main as it is and is a means of folding the feature branch back into main. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1365-gk98di5z.web.app

**Review by orelbn — APPROVED** [review]
Thanks for folding in the changes.

**Review by dimak1 — APPROVED** [review]
🚀

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1365-gk98di5z.web.app

**Review by doug-lovett — APPROVED** [review]
Rock On!

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1365-gk98di5z.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1365-gk98di5z.web.app

**Pull request merged**
