### PR TITLE
Mixed Home Owners error for all Transfers

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#16683

*Description of changes:*
- Added mixed owners validation for all Transfer types (beyond Gift/Sale type)
- Fixed styling for the error
- Updated unit tests (fixed TS errors as well)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1419-auzcueg3.web.app

**Review by cameron-eyds — APPROVED** [review]

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by orelbn — APPROVED** [review]

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1419-auzcueg3.web.app

**Pull request merged**
