### PR TITLE
Make General Collateral required for Income Tax Act registration

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#18303
- bcgov/entity#17491

*Description of changes:*
- Make General Collateral required for Income Tax Act registration
- Add unit test
- Update default text for General Collateral for certain Reg Types

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good!
Does this include the default value, as there was previous talk that was a similar issue or the root cause of this one?

**Review by RuoxuanPengBC — APPROVED** [review]
Looks great!

**Comment by dimak1** [comment]
> Looks good! Does this include the default value, as there was previous talk that was a similar issue or the root cause of this one?

@cameron-eyds thanks for checking, there is a dependency ticket that I picked up, so I will add a fix in this PR as well.

**Comment by dimak1** [comment]
@cameron-eyds I added a default value for Gen Collateral, if you want to take a quick look. Now, once the user lands on that step, it would be immediately valid, because Gen Col is pre-filled (for certain reg types).

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1619-fqnow6wo.web.app

**Pull request merged**
