### PR TITLE
Amendment Fixes + Date Formatting for Safari

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#19071
 /bcgov/entity#18919
 /bcgov/entity#18312

*Description of changes:*
* Fixes Court Order to validate correctly when opening/closing date picker
* FIxes date formatting for Mozilla, to allow TODAY. 
* Fixes/Reformats date output from date picker to be consistent between all browsers (Safari 17.x + was returning non base iso format for it's date, Why? i don't know... comon safari) 
* Fixes minor validation in vehicle collateral to not show bar when it's optional
* Minor UXA items for Transport Permit setup

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1668-4j3hdzgy.web.app

**Review by doug-lovett — APPROVED** [review]
Nice fix, I'm sure the investigation was painful.

**Comment by cameron-eyds** [comment]
> Nice fix, I'm sure the investigation was painful.

Very painful indeed! 
Was a great find by Divya tho

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1668-4j3hdzgy.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1668-4j3hdzgy.web.app

**Pull request merged**
