### PR TITLE
MHR Transfer Details 

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* /bcgov/entity#13818

*Description of changes:*
- MHR Transfer Details component
- Unit Tests
- Partial validation (as it is not a part for this ticket)

### Screenshots

Screen Shot 2022-10-10 at 2 08 00 PM

Screen Shot 2022-10-10 at 2 10 06 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Review by doug-lovett — APPROVED** [review]
Also looks good.

**Review by cameron-eyds — APPROVED** [review]
Looks good to me 👍

**Comment by dimak1** [comment]
Need to merge PR #986 which fixed a bug before merging this request.

**Comment by dimak1** [comment]
@cameron-freshworks just a note for this PR: the valid state for the Transfer Details form is stored in composable, not the state (as in the registration).

**Comment by cameron-eyds** [comment]
> @cameron-freshworks just a note for this PR: the valid state for the Transfer Details form is stored in composable, not the state (as in the registration).

Sounds good, thanks for the heads up.
As this Mhr Information flow grows, it might make sense to relocate/consolidate with other flags in the store, but all good for now 👍

**Pull request merged**
