### PR TITLE
Bill of Sale Transfers Updates

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#18219

*Description of changes:*
- Updates for all Bill of Sale type Transfers
- See ticket for details

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1848-m6ahaj39.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1848-m6ahaj39.web.app

**Pull request merged**
