### PR TITLE
Updated Transfer Draft handling

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#15996

*Description of changes:*|
* Schema update to include additional transfer types, allows the remaining Drafts to be saved/updated
* Fixes Transfer Transfer type on Draft PUT
* Includes bug fix for  /bcgov/entity#16045
* Includes Submitting party in Drafts as per /bcgov/entity#16009

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1315-xwm48fpv.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by dimak1 — APPROVED** [review]

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1315-xwm48fpv.web.app

**Pull request merged**
