### PR TITLE
Minor UX fixes to Qualified Supplier Review and Confirm components

### PR DESCRIPTION
**Pull request by orelbn**
*Issue #:* /bcgov/entity#16839

*Description of changes:*
- Minor styling changes
- Limited legal name field to 150 characters

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1481-k66xo24s.web.app

**Review by doug-lovett — APPROVED** [review]
Very nice.

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Pull request merged**
