### PR TITLE
Cleanup Tax Cert in Transport Permit payload

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#19800

*Description of changes:*
- Cleanup Tax Cert in Transport Permit payload when moving within same park

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1768-wv6d223l.web.app

**Review by doug-lovett — APPROVED** [review]
LGTM.

**Comment by dimak1** [comment]
@cameron-eyds now this is affected with JS memory issue... this shouldn't me merged until it is resolved, I'll continue to investigate

**Review by cameron-eyds — APPROVED** [review]
Looks good

**Comment by cameron-eyds** [comment]
> @cameron-eyds now this is affected with JS memory issue... this shouldn't me merged until it is resolved, I'll continue to investigate

As noted in the other PR, this VITEST issue isn't the result on any code change in these PRs. 
So once again, my recommendation isn't any functional code refactoring, just make the necessary changes and re-run the suite until it passes without the leak. 
We can tackle this intermittent config issue standalone and not block the PRs.

**Comment by dimak1** [comment]
@cameron-eyds you think it's ok to merge once one of test runs is green? Ok, I will re-run.

**Pull request merged**
