### PR TITLE
Permit Help Content Update

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#20243

*Description of changes:*
- Minor text updates to Transport Permit Help Content
- Minor refactors: Removed unused properties, added code comment, removed obsolete rule conditions and corrected some test selectors. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1787-e5fgfa9a.web.app

**Review by dimak1 — APPROVED** [review]

**Review by doug-lovett — APPROVED** [review]

**Comment by cameron-eyds** [comment]
@saragunnarsson Small content update here, ready for UXA if you would like, no rush, thank you!
https://bcregistry-assets-dev--pr-1787-e5fgfa9a.web.app/

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1787-e5fgfa9a.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1787-e5fgfa9a.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1787-e5fgfa9a.web.app

**Pull request merged**
