### PR TITLE
Business LookUp Update

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#16969

*Description of changes:*
* Adjustment to keep the Business LookUp Active for Copy Pasted Text Scenarios to fix previous bug which would disable after clearing the field.
* Minor adjustment to enable copy paste content to trigger Business Lookup for the Mhr Org Name.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1432-7x5je9aq.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by orelbn — APPROVED** [review]
Looks good!

**Review by dimak1 — APPROVED** [review]

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1432-7x5je9aq.web.app

**Pull request merged**
