### PR TITLE
SAN Notice/Orders: Edit/Remove

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:* /bcgov/entity#21109

*Description of changes:*
- Includes Editing and Removal of Notices and Court Orders
- UXA feedback from Court Orders - Includes scroll/spacing, inline editing and new notices at the top of the list
- Includes hide/show btn for Orders
- Minor validation updates

Screenshot 2024-05-21 at 1 41 51 PM

Screenshot 2024-05-21 at 2 04 09 PM

Screenshot 2024-05-21 at 1 42 15 PM

Screenshot 2024-05-21 at 1 42 07 PM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1886-286uri0q.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1886-286uri0q.web.app

**Review by doug-lovett — APPROVED** [review]
Very nice.

**Review by dimak1 — APPROVED** [review]
Looks great!

**Pull request merged**
