### PR TITLE
Transfer Affidavit info on the Review and Confirm

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#16047
- bcgov/entity#15906

*Description of changes:*
- Add Affidavit to Review and Confirm page
- Affidavit submission worked without any additional changes
- Tests will be added later (after some refactoring and when more transfer types are added)
- Typo fix for MHR Reg

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1297-2ygx6q5y.web.app

**Review by cameron-eyds — APPROVED** [review]
LGTM!

**Review by doug-lovett — APPROVED** [review]

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1297-2ygx6q5y.web.app

**Review by owillborn — APPROVED** [review]
looks good!

**Pull request merged**
