### PR TITLE
Fix Additional Name pre-fill

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#16581

*Description of changes:*
- Fix Additional Name when multiple Owners are deleted at once

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1369-3wet4xax.web.app

**Review by orelbn — APPROVED** [review]
Looks good.

**Review by cameron-eyds — APPROVED** [review]
Loooks good!

**Review by doug-lovett — APPROVED** [review]

**Pull request merged**
