### PR TITLE
Scroll to top of Home Owners table

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#20617

*Description of changes:*
- Scroll to top of Home Owners table after Add/Edit Home Owner

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1818-nb8t7z4v.web.app

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Review by doug-lovett — APPROVED** [review]
LG.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1818-nb8t7z4v.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1818-nb8t7z4v.web.app

**Pull request merged**
