### PR TITLE
Update Unit Note dropdown for Exempt MHR

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:* 
- bcgov/entity#19180

*Description of changes:*
- Update Unit Note dropdown (to add Confidential Note) for Exempt MHR
- Remove hardcoded width for the dropdown

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1821-plhv6m49.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by cameron-eyds — APPROVED** [review]
Looks good!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1821-plhv6m49.web.app

**Pull request merged**
