### PR TITLE
15936 update dashboard help link

### PR DESCRIPTION
**Pull request by orelbn**
*Issue #:* /bcgov/entity#15936

*Description of changes:*
- Updates link to open to the anchored portion
- Updates tooltip text

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1318-1msee7hu.web.app

**Review by dimak1 — APPROVED** [review]
🚀 First PR!

**Review by cameron-eyds — APPROVED** [review]
Nice job sir!

When you bump the version in your package.json, you'll need to run an `npm i` to keep the package-lock in sync as well 👍

**Review by doug-lovett — APPROVED** [review]
Tough one.

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1318-1msee7hu.web.app

**Comment by cameron-eyds** [comment]
@orelbn Looks good! Successful rebase/conflict resolution 👍

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-assets-dev--pr-1318-1msee7hu.web.app

**Pull request merged**
